### ISSUE TITLE
Add wrapper types to `io`

### ISSUE THREAD

**Issue by runarorama** [unisonweb/base#10]
This adds `Text` wrapper types `HostName`, `ServiceName`, and `FilePath` and updates relevant `io` operations to use these instead of `Text`.

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk git@github.com:runarorama/bv2:.newtypes

  Updates:

     List.initialize : Nat -> (Nat ->{e} a) ->{e} [a]
     +  unisoncomputing2020 : License

     io.clientSocket : Text -> Text ->{IO, Exception} io.Socket
     ↓
     io.clientSocket : HostName -> ServiceName ->{IO, Exception} io.Socket
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.createDirectory : Text ->{IO, Exception} ()
     ↓
     io.createDirectory : FilePath ->{IO, Exception} ()
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.createTempDirectory : Text ->{IO} Either Failure Text
     ↓
     io.createTempDirectory : FilePath ->{IO, Exception} FilePath
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.fileExists : Text ->{IO, Exception} Boolean
     ↓
     io.fileExists : FilePath ->{IO, Exception} Boolean
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.getCurrentDirectory : '{IO, Exception} Text
     ↓
     io.getCurrentDirectory : '{IO, Exception} FilePath
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.getFileSize : Text ->{IO, Exception} Nat
     ↓
     io.getFileSize : FilePath ->{IO, Exception} Nat
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.getFileTimestamp : Text ->{IO, Exception} Nat
     ↓
     io.getFileTimestamp : FilePath ->{IO, Exception} EpochTime
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.getTempDirectory : '{IO, Exception} Text
     ↓
     io.getTempDirectory : '{IO, Exception} FilePath
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.isDirectory : Text ->{IO, Exception} Boolean
     ↓
     io.isDirectory : FilePath ->{IO, Exception} Boolean
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.openFile : Text -> FileMode ->{IO, Exception} io.Handle
     ↓
     io.openFile : FilePath -> FileMode ->{IO, Exception} io.Handle
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.removeDirectory : Text ->{IO, Exception} ()
     ↓
     io.removeDirectory : FilePath ->{IO, Exception} ()
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.removeFile : Text ->{IO, Exception} ()
     ↓
     io.removeFile : FilePath ->{IO, Exception} ()
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.renameDirectory : Text -> Text ->{IO, Exception} ()
     ↓
     io.renameDirectory : FilePath -> FilePath ->{IO, Exception} ()
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.renameFile : Text -> Text ->{IO, Exception} ()
     ↓
     io.renameFile : FilePath -> FilePath ->{IO, Exception} ()
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.serverSocket : Optional Text -> Text ->{IO, Exception} io.Socket
     ↓
     io.serverSocket : Optional HostName -> ServiceName ->{IO, Exception} io.Socket
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.setCurrentDirectory : Text ->{IO, Exception} ()
     ↓
     io.setCurrentDirectory : FilePath ->{IO, Exception} ()
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     io.socketPort : io.Socket ->{IO} Either Failure Nat
     ↓
     io.socketPort : io.Socket ->{IO, Exception} Nat
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     patch patch (added 19 updates)

  Added definitions:

     unique type io.FilePath
     unique type io.HostName
     unique type io.ServiceName
     io.HostName.HostName       : Text -> HostName
     io.ServiceName.ServiceName : Text -> ServiceName
     io.FilePath.toText         : FilePath -> Text (+2 metadata)
     io.HostName.doc            : Doc (+2 metadata)
     io.HostName.toText         : HostName -> Text (+2 metadata)
     io.ServiceName.doc         : Doc (+2 metadata)
     io.ServiceName.toText      : ServiceName -> Text (+2 metadata)
     io.clientSocket.doc        : Doc (+2 metadata)

  Removed definitions:

     io.getTemporaryDirectory : '{IO, Exception} Text

  Name changes:

    Original                   Changes
     io.createTempDirectory     io.createTempDirectory.impl (added)
                                io.createTempDirectory (removed)

     io.socketPort              io.socketPort.impl (added)
                                io.socketPort (removed)

**Comment by pchiusano** [comment]
@runarorama Okay this is done in #7nm8vn4nu3

I left the old versions around for now, adding `.deprecated` to their names.

I also left the patch alone so this isn't a forced upgrade.

Overall namespace fixup is super painful and I really want some version of https://github.com/unisonweb/unison/issues/1995
