### ISSUE TITLE
Update tour and contributing docs

### ISSUE THREAD

**Issue by bobholt** [unisonweb/base#100]
This PR is intended to update `unison.public.website.learn.tour` and `unison.public.website.learn.contributeDocs`. My changes do not all appear to be represented in the output below, but are visible in on https://share.unison-lang.org/@bobholt/code/latest/terms/public/prs/learn/_updateTour/. I'll summarize the changes in addition to the Code review below:

- changed references to `base.List` and `base.Heap` to `base.data.List` and `base.data.Heap` throughout `tour`
- removed leading dot before `square.tests` in `move.namespace square.tests mySquare.tests` in `tour#Moving and renaming terms`
- changed remaining references to `_docs` to `_learn` in `contributeDocs`
- changed recommendation of `.> push git(git@github.com:myuser/allmyunisoncode)` to `.> push.create myuser.public.prs .prs` on Unison Share due to https://github.com/unisonweb/unison/issues/3251 (which I ran into trying to `push.create` to GitHub)

I did not intend to change the license, but followed the instructions in `contributeDocs`. I'd love to get feedback on how to prevent that.

## Code review

  The changes summarized below are available for you to review, using the
  following command:

```
    pull-request.load unison.public.website.learn bobholt.public.prs.learn._updateTour
```

```
  Updates:

     contributeDocs : Doc
     ↓
     contributeDocs : Doc
     +  bobholt2022     : metadata.License
     +  authors.bobholt : metadata.Author

    There were 10 auto-propagated updates.

     patch patch (added 14 updates, deleted 14)
```

**Comment by rlmark** [comment]
Awesome! I'll take a look now!

**Comment by rlmark** [comment]
Thank you @bobholt! This has been merged and deployed to prod.
