### ISSUE TITLE
Stream.flatMap changes

### ISSUE THREAD

**Issue by anovstrup** [unisonweb/base#103]
This PR:
* Generalizes `Stream.flatMap` & `Stream.flatMap!` (see #101)
* Adds `Stream.concatMap` & `Stream.concatMap!`, implemented in terms of `Stream.flatMap!`
* Fixes some Stream docs (see #102)
* Reimplements `Stream.filter!` in terms of `Stream.concatMap!`

## Code review

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load unison.public.base.main anovstrup.public.prs.base.streamFlatMap
  
  Updates:
  
     abilities.repeat : Nat -> '{e} a ->{e} ()
     -  M4.abilities.repeat.doc : Doc
     +  abilities.repeat.doc    : Doc
    
     data.Stream.filter! : (a ->{g} Boolean) -> '{g, Stream a} r ->{g, Stream a} r
     ↓
     data.Stream.filter! : (a ->{g} Boolean) -> '{g, Stream a} r ->{g, Stream a} r
     +  authors.anovstrup                     : Author
     +  metadata.licenses.anovstrup.mit_2020  : metadata.License
     +  .metadata.licenses.anovstrup.mit_2020 : M1m.License
    
     data.Stream.filter!.doc : Doc
     ↓
     data.Stream.filter!.doc : Doc
     +  authors.anovstrup                     : Author
     +  metadata.licenses.anovstrup.mit_2020  : metadata.License
     +  .metadata.licenses.anovstrup.mit_2020 : M1m.License
    
     data.Stream.flatMap : (a ->{e, Stream b} r) -> '{e, Stream a} r -> '{e, Stream b} r
     ↓
     data.Stream.flatMap : (a ->{e, Stream b} any) -> '{e, Stream a} r -> '{e, Stream b} r
     +  metadata.licenses.chrispenner         : metadata.License
     +  authors.chrispenner                   : Author
     +  authors.anovstrup                     : Author
     +  metadata.licenses.anovstrup.mit_2020  : metadata.License
     +  .metadata.licenses.anovstrup.mit_2020 : M1m.License
    
     data.Stream.flatMap! : (a ->{e, Stream b} r) -> '{e, Stream a} r ->{e, Stream b} r
     ↓
     data.Stream.flatMap! : (a ->{e, Stream b} any) -> '{e, Stream a} r ->{e, Stream b} r
     +  authors.anovstrup                     : Author
     +  metadata.licenses.anovstrup.mit_2020  : metadata.License
     +  .metadata.licenses.anovstrup.mit_2020 : M1m.License
    
     data.Stream.flatMap!.doc : Doc
     ↓
     data.Stream.flatMap!.doc : Doc
     +  authors.anovstrup                     : Author
     +  metadata.licenses.anovstrup.mit_2020  : metadata.License
     +  .metadata.licenses.anovstrup.mit_2020 : M1m.License
    
     data.Stream.flatMap.doc : Doc
     ↓
     data.Stream.flatMap.doc : Doc
     +  authors.anovstrup                     : Author
     +  metadata.licenses.anovstrup.mit_2020  : metadata.License
     +  .metadata.licenses.anovstrup.mit_2020 : M1m.License
  
    There were 39 auto-propagated updates.
  
  Added definitions:
  
     data.Stream.concatMap      : (a ->{e} [b])
                                -> '{e, Stream a} r
                                -> '{e, Stream b} r (+2 metadata)
     data.Stream.concatMap!     : (a ->{e} [b]) -> '{e, Stream a} r ->{e, Stream b} r (+2 metadata)
     data.Stream.concatMap.doc  : Doc (+2 metadata)
     data.Stream.concatMap!.doc : Doc (+2 metadata)

**Comment by ceedubs** [comment]
Thanks @anovstrup! These changes look good to me.

`Stream` could definitely use some more unit tests, and adding some for `concatMap` might be a good place to start, as it will transitively test some other functions like `flatMap`.

@runarorama do you want me to go ahead and push this change or do you want to take a look?

**Comment by runarorama** [comment]
Push it!

**Comment by ceedubs** [comment]
Merged to `base.main` as of `#r4p564erqm`!
