### ISSUE TITLE
Float.toNat is broken

### ISSUE THREAD

**Issue by mgladdish** [unisonweb/base#104]
Float.toNat says it 

> Converts a Float to a Nat by dropping any fractional amount and ignoring negative numbers.

But its implementation doesn't appear to do that. Even with the examples given in the docs.

`Float.toNat 3.99` should be `Some 3` but it's actually `Some 1`

**Comment by runarorama** [comment]
Fixed in `main` branch as of hash `#irtems4ssa`.

```
  # Examples

        Float.toNat 1.0
        ⧨
        Some 1

        Float.toNat 3.99
        ⧨
        Some 3
```
