### ISSUE TITLE
Add functions for catching runtime exceptions

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#107]
This adds an `io.tryEval.impl` alias for the `##IO.tryEval` that was added in https://github.com/unisonweb/unison/pull/3365 .

It also adds a couple of helper functions and some docs.

- [tryEval.impl](https://share.unison-lang.org/@ceedubs/code/latest/namespaces/public/pr/base/tryEval/;/terms/io/tryEval/impl)
- [tryEval](https://share.unison-lang.org/@ceedubs/code/latest/namespaces/public/pr/base/tryEval/;/terms/io/tryEval)
- [catchAll](https://share.unison-lang.org/@ceedubs/code/latest/namespaces/public/pr/base/tryEval/;/terms/io/catchAll)

## Code review

 The changes summarized below are available for you to review, using the following command:
  
    pull-request.load unison.public.base.main ceedubs.public.pr.base.tryEval
  
  Added definitions:
  
     io.catchAll         : '{IO, Exception} a ->{IO} Either Failure a (+2 metadata)
     io.catchAll.doc     : Doc (+2 metadata)
     io.tryEval.impl.doc : Doc (+2 metadata)
     io.tryEval.doc      : Doc (+2 metadata)
     io.tryEval.impl     : '{IO} a ->{IO, Exception} a
     io.tryEval          : '{IO, Exception} a ->{IO, Exception} a (+2 metadata)

**Comment by ceedubs** [comment]
I've added some tests, but they won't pass until https://github.com/unisonweb/unison/pull/3413 is merged.

**Comment by ceedubs** [comment]
https://github.com/unisonweb/unison/pull/3413 is merged, so this should be good to go @runarorama

**Comment by runarorama** [comment]
Pushed to `main` as hash `#po9hhb74mh`

🌈⭐
