### ISSUE TITLE
doc for test.ensure' is wrong

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#108]
https://share.unison-lang.org/@unison/code/latest/namespaces/public/base/latest/;/terms/@9cu0pmpkvall4es4hvstgm5t57vaa4hovp2i4m1ukp6898ngign8eq9vr5a8v79go3tgpttehicl21innishmqp387oc2j8mcgj88ro

It states `ensure' msg true returns ()`, but it actually returns `msg`.

I didn't submit a fix because I'm not sure whether we should change the doc or or the return type. It kinda feels like it should return `()`.

**Comment by runarorama** [comment]
I changed the return type to `()`. It's unlikely that anyone is relying on the return type being the type of the message.
