### ISSUE TITLE
More `data.ByteArray` functionality

### ISSUE THREAD

**Issue by dolio** [unisonweb/base#109]
This PR adds various `data.ByteArray` functions. They are motivated primarily by a port of unison's internal representation of `Bytes` to pure unison that I'm working on. Some tests are also included.

## Code review

  The changes summarized below are available for you to review, using the
  following command:

    pull-request.load unison.public.base.main dolio.public.base.vector

  Updates:

     patch patch (added 3 updates)

  Added definitions:

     ┌ data.ByteArray.++               : data.ByteArray
                                       -> data.ByteArray
                                       -> data.ByteArray (+2 metadata)
     └ data.ByteArray.append           : data.ByteArray
                                       -> data.ByteArray
                                       -> data.ByteArray (+2 metadata)
     data.ByteArray.++.doc             : Doc (+2 metadata)
     data.ByteArray.drop.doc           : Doc (+2 metadata)
     data.ByteArray.join.doc           : Doc (+2 metadata)
     data.ByteArray.new!.doc           : Doc (+2 metadata)
     data.ByteArray.Raw.new!.doc       : Doc (+2 metadata)
     data.ByteArray.read16be.doc       : Doc (+2 metadata)
     data.ByteArray.read32be.doc       : Doc (+2 metadata)
     data.ByteArray.read64be.doc       : Doc (+2 metadata)
     data.ByteArray.take.doc           : Doc (+2 metadata)
     data.ByteArray.Raw.toByteList.doc : Doc (+2 metadata)
     data.ByteArray.Raw.toBytes.doc    : Doc (+2 metadata)
     mutable.ByteArray.write16be.doc   : Doc (+2 metadata)
     mutable.ByteArray.write32be.doc   : Doc (+2 metadata)
     mutable.ByteArray.write64be.doc   : Doc (+2 metadata)
     data.ByteArray.drop               : Nat
                                       -> data.ByteArray
                                       -> data.ByteArray (+2 metadata)
     data.ByteArray.join               : [data.ByteArray]
                                       -> data.ByteArray (+2 metadata)
     data.ByteArray.new!               : Nat
                                       -> (∀ s.
                                         mutable.ByteArray (mutable.Scope s)
                                         ->{Exception, mutable.Scope s} ())
                                       -> data.ByteArray (+2 metadata)
     data.ByteArray.Raw.new!           : Nat
                                       -> (∀ s.
                                         mutable.ByteArray.Raw
                                           (mutable.Scope s)
                                         ->{Exception, mutable.Scope s} ())
                                       -> data.ByteArray.Raw (+2 metadata)
     data.ByteArray.read16be           : data.ByteArray
                                       -> Nat
                                       ->{Exception} Nat (+2 metadata)
     data.ByteArray.read32be           : data.ByteArray
                                       -> Nat
                                       ->{Exception} Nat (+2 metadata)
     data.ByteArray.read64be           : data.ByteArray
                                       -> Nat
                                       ->{Exception} Nat (+2 metadata)
     data.ByteArray.take               : Nat
                                       -> data.ByteArray
                                       -> data.ByteArray (+2 metadata)
     data.ByteArray.append.test        : [test.Result] (+3 metadata)
     data.ByteArray.drop.test          : [test.Result] (+3 metadata)
     data.ByteArray.join.test          : [test.Result] (+3 metadata)
     data.ByteArray.size.test          : [test.Result] (+3 metadata)
     data.ByteArray.take.test          : [test.Result] (+3 metadata)
     data.ByteArray.toList.test        : [test.Result] (+3 metadata)
     data.ByteArray.Raw.toByteList     : data.ByteArray.Raw
                                       -> [Nat] (+2 metadata)
     data.ByteArray.Raw.toBytes        : data.ByteArray.Raw
                                       -> Bytes (+2 metadata)
     mutable.ByteArray.write16be       : mutable.ByteArray g
                                       -> Nat
                                       -> Nat
                                       ->{g, Exception} () (+2 metadata)
     mutable.ByteArray.write32be       : mutable.ByteArray g
                                       -> Nat
                                       -> Nat
                                       ->{g, Exception} () (+2 metadata)
     mutable.ByteArray.write64be       : mutable.ByteArray g
                                       -> Nat
                                       -> Nat
                                       ->{g, Exception} () (+2 metadata)

**Comment by runarorama** [comment]
Merged into `main` 🌈⭐
