### ISSUE TITLE
`Tls` type has no documentation

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#110]
https://share.unison-lang.org/@unison/code/latest/namespaces/public/base/latest/;/types/io/Tls

@stew maybe you could take a crack at this since I think you've actually used the API?

**Comment by pchiusano** [comment]
Also `ClientConfig` has no docs.

**Comment by runarorama** [comment]
I've added docs for both of these:

https://share.unison-lang.org/@unison/code/latest/namespaces/public/base/main/;/types/@@Tls
