### ISSUE TITLE
missing name for `##Bytes.fromBase64UrlUnpadded`

### ISSUE THREAD

**Issue by aryairani** [unisonweb/base#118]
This builtin is referenced by `Bytes.fromBase64UrlUnpadded.doc`

It looks like the name `Bytes.frombase64UrlUnpadded` was present in `releases.M4` but is not in `main`.

**Comment by pchiusano** [comment]
@runarorama I could have sworn you added this when we were jamming earlier, but I bet you just forgot to push.

**Comment by runarorama** [comment]
I think this is an issue with merge somehow. The name is in my codebase and I have no diffs with upstream Base on Share.

**Comment by runarorama** [comment]
<img width="888" alt="image" src="https://user-images.githubusercontent.com/130916/195668790-2181e0f6-1a38-4f6c-802e-7daa96345551.png">

**Comment by runarorama** [comment]
Looks like I resolved the issue by doing the following:

1. Move the term to another name.
2. Push
3. Move it back.
4. Push again.

**Comment by aryairani** [comment]
Hm :-\ ok (re merge weirdness)
Thanks!
