### ISSUE TITLE
Random number generating ability

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#12]
pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/pchiusano/unisoncode:.prs.random2

We started on this during office hours the other day and I got it polished up. Here's the final interface:

```Haskell
ability Random where
  nat : Nat
  bytes : Nat -> Bytes
  split : {Random} (forall g a. '{Random,g} a ->{g} a)
```

The RNG state and update rule is encapsulated in the handler of the ability. This works out nicer than using something like `Store` / `State` where the RNG state leaks into the API.

This PR just has one handler based on a linear congruential generator but it would be great to get other implementations. (Like @atacratic has a mersenne twister implementation - would you like to port that to this API?)

The implementation uses helper functions from #11. Kinda cool is that this could still be merged ahead of #11 and those functions will just show up as unnamed... then when #11 gets merged it'll start using the newly provided names for the functions. Though I think it would be nice during PR review to get a warning about relying on unnamed definitions, or maybe `todo` could report on that.

## Future work

We didn't get too far on writing helper functions for generating different kinds of values. (Like floating point numbers with various distributions would be good).

<img width="965" alt="Screen Shot 2021-06-09 at 10 42 57 PM" src="https://user-images.githubusercontent.com/11074/121462116-b467f300-c975-11eb-95b2-59aa411a52d0.png">
<img width="1101" alt="Screen Shot 2021-06-09 at 10 43 16 PM" src="https://user-images.githubusercontent.com/11074/121462117-b467f300-c975-11eb-825a-3574b8cdd80f.png">
<img width="681" alt="Screen Shot 2021-06-09 at 10 43 39 PM" src="https://user-images.githubusercontent.com/11074/121462118-b5008980-c975-11eb-84d1-af91bf1cca9b.png">
<img width="838" alt="Screen Shot 2021-06-09 at 10 43 52 PM" src="https://user-images.githubusercontent.com/11074/121462119-b5008980-c975-11eb-9d8f-8a59067f3bcc.png">
  
  Added definitions:
  
     ability Random (+2 metadata)
     Random.bytes                  : Nat ->{Random} Bytes
     Random.nat.impl               : {Random} Nat
     Random.split.impl             : {Random} (∀ g a. '{g, Random} a ->{g} a)
     Random.boolean                : '{Random} Boolean (+2 metadata)
     Random.boolean.doc            : Doc (+2 metadata)
     Random.bytes.doc              : Doc (+2 metadata)
     Random.doc                    : Doc (+2 metadata)
     Random.impl.bytesFromNats     : '{g, Random} Nat -> Nat ->{g, Random} Bytes (+2 metadata)
     Random.impl.bytesFromNats.doc : Doc (+2 metadata)
     Random.lcg                    : Nat -> '{g, Random} a ->{g} a (+2 metadata)
     Random.lcg.doc                : Doc (+2 metadata)
     Random.lcg.handler            : Nat -> Request {Random} a -> a (+2 metadata)
     Random.lcg.handler.doc        : Doc (+2 metadata)
     Random.nat                    : '{Random} Nat (+2 metadata)
     Random.nat.doc                : Doc (+2 metadata)
     Random.natIn                  : Nat -> Nat ->{Random} Nat (+2 metadata)
     Random.natIn.doc              : Doc (+2 metadata)
     Random.natIn.tests.ex1        : [Result] (+3 metadata)
     Random.split                  : '{Random} '{g, Random} t ->{g} t (+2 metadata)
     Random.split.doc              : Doc (+2 metadata)

**Comment by atacratic** [comment]
I'm not sure that the `split` API is appropriate for other PRNGs [edit] than splitmix.  AIUI from the splitmix [paper](http://gee.cs.oswego.edu/dl/papers/oopsla14.pdf) it was a novel feature.  Sure there are plausible ways of reseeding other PRNGs to give similar behaviour, like I see you're doing with lcg here, but I doubt there'd be much guarantee of the quality and independence of the resultant random number streams - not by cryptographic/statistical standards anyway.  Is that OK?

Minor thing: when I pull this I see `.impl` in the names of a couple of the operations - expected?
```
._prs_review.base_pchiusano_random2.head> view Random

  ability Random where
    split.impl : {Random} (∀ g a. '{g, Random} a ->{g} a)
    nat.impl : {Random} Nat
    bytes : Nat ->{Random} Bytes

```

**Comment by atacratic** [comment]
Meh, I guess it is good to have `split` in here - certainly makes programming better; and even if there are otherwise  cryptographically/statistically strong PRNGs that can't provide a strong `split` implementation, they don't have to implement this API, and if they do they can comment with a warning.

**Comment by pchiusano** [comment]
Yeah I think it's okay if some handlers don't have a great implementation of split and that can just be noted in their docs... in fact let me note that for the lcg handler.

**Comment by pchiusano** [comment]
Actually, I was noodling on this, and I think a better idea for `split` is to apply some actually vetted hashing function to the seed / state. Maybe https://hackage.haskell.org/package/murmur-hash-0.1.0.9/docs/src/Data-Digest-Murmur64.html#hash64AddWord64

**Comment by pchiusano** [comment]
I've refreshed this PR:

* It now uses murmur hash (#14) to implement splitting of the linear congruential generator
* It now includes an implementation of SplitMix, another common RNG which has a more native implementation of splitting
* I've added `Random.Readme` to give an overview of the namespace

<img width="616" alt="Screen Shot 2021-06-16 at 9 12 39 PM" src="https://user-images.githubusercontent.com/11074/122320314-a96a1100-cee7-11eb-941e-3f268d1da0d1.png">

**Comment by pchiusano** [comment]
@runarorama I made a few tweaks to the readme based on your feedback - I adding a couple sections to call out categories of functions in the namespace.

<img width="618" alt="Screen Shot 2021-06-16 at 10 49 09 PM" src="https://user-images.githubusercontent.com/11074/122328398-310a4c80-cef5-11eb-9d6d-45b31b9667d0.png">

Aside: for PR review, assuming we keep using GitHub for a while longer, I think we could get mileage out of https://github.com/unisonweb/unison/issues/2098 to produce nice markdown from rendered docs. Taking screenshots of the output of `display` is janky.

**Comment by runarorama** [comment]
Merged to `trunk` in hash `#pjdnqduc38`.

This PR was missing a name for the `Random` ability, so I added it.
