### ISSUE TITLE
Map.Nonempty and Set.Nonempty?

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#121]
I just found myself wishing that I had a `Set.Nonempty` similar to `List.Nonempty`. Is this something that anyone else has found themselves wishing they had? It looks like `Set` is implemented in terms of `Map`, so if we were to add one I'd imagine that we'd add the other.

**Comment by runarorama** [comment]
What do you think of:

```
Nonempty f a = Nonempty a (f a)
```

**Comment by runarorama** [comment]
OK, just convinced myself that will not work :)

**Comment by ceedubs** [comment]
Even if it _would_ work my experience with this sort of structure in the Scala world was that it worked well for cons-lists (other than adding some indirection that could be confusing to newcomers), but it was a little bit awkward for pretty much any other structure (performance, one-off methods to support a specific collection type, etc).

**Comment by runarorama** [comment]
Nonempty maps are here: https://share.unison-lang.org/@unison/code/latest/namespaces/public/base/main/;/types/data/Map/Nonempty

**Comment by runarorama** [comment]
Here's nonempty set: https://share.unison-lang.org/@unison/code/latest/namespaces/public/base/main/;/types/data/Set/Nonempty
