### ISSUE TITLE
Very sad and lonely docs for TQueue

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#123]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/11074/200426399-cc7e0563-edde-4347-b81d-ff3fb5b878b0.png">

https://share.unison-lang.org/@unison/code/latest/namespaces/public/base/latest/;/types/IO/concurrent/STM/TQueue

**Comment by runarorama** [comment]
Cheer up: https://share.unison-lang.org/@unison/code/latest/namespaces/public/base/main/;/types/IO/concurrent/STM/TQueue

**Comment by pchiusano** [comment]
nice!
