### ISSUE TITLE
Text.head and Text.charAt

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#125]
`Text.charAt` is similar to `List.at` and we found ourselves wanting it when working on Advent of Code problems in community day. It could probably be implemented more efficiently as a builtin, but I figured that this performance shouldn't be too awful, and it's useful to have in base now even if it gets added as a builtin later.

## Code review

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load unison.public.base.main ceedubs.public.pr.base.text_head
  
  Added definitions:
  
     Text.charAt       : Nat -> Text -> Optional Char (+2 metadata)
     Text.charAt.doc   : Doc (+2 metadata)
     Text.head.doc     : Doc (+2 metadata)
     Text.head         : Text -> Optional Char (+2 metadata)
     Text.charAt.tests : [test.Result] (+3 metadata)
     Text.head.tests   : [test.Result] (+3 metadata)

**Comment by runarorama** [comment]
Merged into `main`. Thanks! 🌈⭐
