### ISSUE TITLE
Remove Heap

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#126]
There was a discussion on Slack about `Heap`. Some takeaways:

- It should be `unique`, not `structural` (mostly because it has ordering constraints that aren't captured by the structure).
- It's a max heap and there's not a general way to use it as a min heap, because it relies on universal comparisons.
- @runarorama and @pchiusano both thought that it should be removed from base (and that someone should create a good `Heap` library)

So it sounds like step 1 is removing it. Step 0 is deciding how to do that. Do we just rip it out or do we move it to a deprecated namespace for a while?

**Comment by ceedubs** [comment]
If there's a good replacement library, it might be helpful to leave a `Heap.doc` that mentions that `Heap` was removed from base but links to the new library.

**Comment by runarorama** [comment]
Should move to deprecated and remove it entirely in a few months

**Comment by runarorama** [comment]
I've moved to `data.deprecated.Heap` and removed all dependencies on this type from other places in Base. Added a note in the doc about deprecation, with a link to Stew's Heap type.
