### ISSUE TITLE
Add Stream.grouped and Stream.grouped!

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#129]
## Code review
  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load unison.public.base.main ceedubs.public.pr.base.stream_grouped
  
  Added definitions:
  
     data.Stream.grouped.doc   : Doc (+2 metadata)
     data.Stream.grouped!.doc  : Doc (+2 metadata)
     data.Stream.grouped       : Nat
                               -> '{g, Stream a} r
                               -> '{g, Stream (List.Nonempty a)} r (+2 metadata)
     data.Stream.grouped!      : Nat
                               -> '{g, Stream a} r
                               ->{g, Stream (List.Nonempty a)} r (+2 metadata)
     data.Stream.grouped.tests : [test.Result] (+3 metadata)

**Comment by runarorama** [comment]
I renamed these to `chunk` instead of `grouped` for consistency with `List` API.

Otherwise looks great! Merged into Base.

🌈 ⭐
