### ISSUE TITLE
generalize signature of test.validate

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#130]
In my case I wanted my predicate to have the `{Exception}` ability and let it bubble through.

## Code review

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load unison.public.base.main ceedubs.public.pr.base.validate_signature
  
  Updates:
  
     test.validate : 'Boolean ->{Exception} ()
     ↓
     test.validate : '{g} Boolean ->{g, Exception} ()
     +  metadata.licenses.unisoncomputing2022 : metadata.License
     +  runarorama                            : Author
     +  authors.ceedubs                       : Author
  
    There were 2 auto-propagated updates.
  
     patch patch (added 1 updates)

**Comment by runarorama** [comment]
Merged into main. Thanks! 🌈⭐
