### ISSUE TITLE
Remove misleading statement from List.transpose docs

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#133]
Before the docs said :

> `transpose rows` swaps the rows and columns of a list of lists, which has the effect of rotating it counerclockwise.

This isn't generally true, but it looked true in the beautiful visual example because of symmetry. I've updated the text and example which you can see here: https://share.unison-lang.org/@ceedubs/p/code/latest/namespaces/public/pr/base/transpose_docs/;/terms/data/List/transpose

# Code Review

I don't really understand why it says this change was auto-propagated. Maybe because of how editing docs works?

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load unison.public.base.main ceedubs.public.pr.base.transpose_docs
  
  Updates:
  
    There were 1 auto-propagated updates.
  
     patch patch (added 1 updates)

**Comment by runarorama** [comment]
Hmm.. this statement is not true either:

> Each cell with coordinates `(x, y)` will be translated to coordinates `(y, x)`

For example: in `transpose [[1,2],[3],[4,5]] = [[1,3,4],[2,5]]`, the `5` goes from `(2,2)` to `(1,2)`.

I've replaced with the following:

    {{
    ``transpose rows`` swaps the rows and columns of a list of lists. The
    result is a list of lists, where the first list contains the first
    elements of each of the input lists, the second list contains the
    second elements, and so on.

    If any of the input lists are empty, they are ignored.
    
    # Examples
    
      ```
      transpose [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
      ```
    
      If the list is rectangular (all its rows are the same length), then 
      we can think of this as a rotation of the list of lists by 90 degrees
      clockwise followed by a horizontal flip, or equivalently a
      rotation by 90 degrees counter-clockwise followed by a vertical flip:
    
      ```
      map
        fromCharList
        (transpose
          (map
            toCharList
            [ "⬜🟥🟥⬜⬜⬜🟥🟥⬜",
              "🟥🟥🟥🟥⬜🟥🟥🟥🟥",
              "🟥🟥🟥🟥🟥🟥🤖🟥🟥",
              "🟥🟥🟥🟥🟥🟥🟥🟥🟥",
              "⬜🟥🟥🟥🟥🟥🟥🟥⬜",
              "⬜⬜🟥🟥🟥🟥🟥⬜⬜",
              "⬜⬜⬜🟥🟥🟥⬜⬜⬜",
              "⬜⬜⬜⬜🟥⬜⬜⬜⬜" ]))
      ```

      However, this intution does not quite work if the lists are not all
      the same length:

      ```
      map
        fromCharList
        (transpose
          (map
            toCharList
            [ "⬜🟥🟥⬜⬜⬜🟥🟥",
              "🟥🟥🟥🟥⬜🟥🟥🟥🟥",
              "🟥🟥🟥🟥🟥🟥🤖🟥🟥",
              "🟥🟥🟥🟥🟥🟥🟥🟥🟥",
              "⬜🟥🟥🟥🟥🟥🟥🟥",
              "⬜⬜🟥🟥🟥🟥🟥",
              "⬜⬜⬜🟥🟥🟥",
              "⬜⬜⬜⬜🟥",
              ""]))
      ```
    }}

**Comment by ceedubs** [comment]
@runarorama ah good catch. I wasn't thinking about non-square cases. Thanks!
