### ISSUE TITLE
Add Stream.changes and related functions

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#135]
This adds a `data.Stream.changes` function that transforms a stream into one that only emits elements that differ from the previous element.

You can start [here](https://share.unison-lang.org/@ceedubs/p/code/latest/namespaces/public/pr/base/stream_changes/;/terms/data/Stream/changes) and click around to see it on Share.

## Code review

 The changes summarized below are available for you to review, using the following command:
  
    pull-request.load unison.public.base.main ceedubs.public.pr.base.stream_changes
  
  Added definitions:
  
     data.Stream.changes                    : Boolean
                                            -> '{g, Stream a} r
                                            -> '{g, Stream a} r (+2 metadata)
     data.Stream.changes!                   : Boolean
                                            -> '{g, Stream a} r
                                            ->{g, Stream a} r (+2 metadata)
     data.Stream.changesBy                  : (a -> a -> Boolean)
                                            -> Boolean
                                            -> '{g, Stream a} r
                                            -> '{g, Stream a} r (+2 metadata)
     data.Stream.changesBy!                 : (a -> a -> Boolean)
                                            -> Boolean
                                            -> '{g, Stream a} r
                                            ->{g, Stream a} r (+2 metadata)
     data.Stream.changes.doc                : Doc (+2 metadata)
     data.Stream.changes!.doc               : Doc (+2 metadata)
     data.Stream.changesBy.doc              : Doc (+2 metadata)
     data.Stream.changesBy!.doc             : Doc (+2 metadata)
     data.Stream.changes.tests.multiple     : [test.Result] (+3 metadata)
     data.Stream.changes.tests.pair         : [test.Result] (+3 metadata)
     data.Stream.changes.tests.repeatSingle : [test.Result] (+3 metadata)
     data.Stream.changes.tests.single       : [test.Result] (+3 metadata)

**Comment by runarorama** [comment]
Merged into `main`. Thanks! 🌈🌟
