### ISSUE TITLE
Add Text.contains: Text -> Text -> Boolean

### ISSUE THREAD

**Issue by justjoheinz** [unisonweb/base#138]
base contains Text.indexOf which returns an Optional Nat. However for many filter applications it would be beneficial to have a normal boolean predicate.

## Code review

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load unison.public.base.latest justjoheinz.public.prs.base.textcontains
  
  Updates:
  
     patch patch (added 1 updates)
  
  Added definitions:
  
     Text.contains                         : Text -> Text -> Boolean
     Text.contains.doc                     : Doc
     metadata.authors.justjoheinz.guid     : GUID
     metadata.authors.justjoheinz          : Author
     metadata.copyrightHolders.justjoheinz : CopyrightHolder
     metadata.licenses.justjoheinz         : License

**Comment by runarorama** [comment]
Merged into the `main` branch. Thanks! 🌈⭐
