### ISSUE TITLE
MurmurHash implementation

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#14]
This was a straightforward port of https://hackage.haskell.org/package/murmur-hash-0.1.0.9/docs/src/Data-Digest-Murmur64.html#hash64AddWord64 and I linked the creator of that package as an additional author in the metadata.

I was having a hard time finding test vectors for this. It might be that this is what I want: https://github.com/yuanzzx/murmurhash-java/blob/master/src/test/java/ie/ucd/murmur/MurmurHashTest.java but there are a number of variants of this hashing algorithm so I'll need to look into that.

  The changes summarized below are available for you to review, using the following
  command:
  
    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/pchiusano/unisoncode:.prs.murmur
  
  Added definitions:
  
     MurmurHash.Readme                         : Doc (+2 metadata)
     MurmurHash.add                            : Nat -> Nat -> Nat (+3 metadata)
     MurmurHash.add.doc                        : Doc (+2 metadata)
     MurmurHash.finish                         : Nat -> Nat (+3 metadata)
     MurmurHash.finish.doc                     : Doc (+2 metadata)
     MurmurHash.impl.murmur_m                  : Nat (+3 metadata)
     MurmurHash.impl.murmur_r                  : Nat (+3 metadata)
     MurmurHash.initialSeed                    : Nat (+2 metadata)
     metadata.authors.thomasschilling          : Author
     metadata.authors.thomasschilling.guid     : GUID
     metadata.copyrightHolders.thomasschilling : CopyrightHolder

```
.prs.murmur> display MurmurHash.Readme

  This namespace has a 64-bit murmur hash implementation. Use `add` to mix a Nat into
  the hash, and finish to finalize the hash, producing a 64-bit Nat.
  
      MurmurHash.add initialSeed 2 |> MurmurHash.add 329048 |> finish
      ⧨
      9723437166784648328
  
  You can use any value to initialize the hash.
  
  # Credits
  
    Implementation is a port of this Haskell library by Thomas Schilling, which is
    BSD-licensed.
```

**Comment by pchiusano** [comment]
@runarorama I made a few tweaks to the readme based on your feedback - I adding a couple sections to call out categories of functions in the namespace.

<img width="618" alt="Screen Shot 2021-06-16 at 10 49 09 PM" src="https://user-images.githubusercontent.com/11074/122328398-310a4c80-cef5-11eb-9d6d-45b31b9667d0.png">

Aside: for PR review, assuming we keep using GitHub for a while longer, I think we could get mileage out of https://github.com/unisonweb/unison/issues/2098 to produce nice markdown from rendered docs. Taking screenshots of the output of `display` is janky.

**Comment by runarorama** [comment]
Merged to `trunk` in hash `#c27a3556dp`
