### ISSUE TITLE
Add functions for reading an entire file and closing it

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#143]
Suggest just rolling these into base, it makes me kind of sad that these need a separate library when they are very uncontroversial and this is like 94% of all file I/O people do. :) 

https://share.unison-lang.org/@chrispenner/p/code/latest/namespaces/public/file/releases/v0_2_0

**Comment by runarorama** [comment]
Merged these functions into Base/main:

https://share.unison-lang.org/@unison/p/code/latest/namespaces/public/base/main/;/types/@i734n6npgnivrl3she2qu7nofhlaej95hoc4vri2j94bla3g9dq3811p2oonqdtvclmbu7hmu6oofffhlaa8923g6mm4umrkvdpt450
