### ISSUE TITLE
Add Bytes.splitAt

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#145]
This adds `Bytes.splitAt`, similar to the existing `Text.splitAt`.

You can see it on Share [here](https://share.unison-lang.org/@ceedubs/p/code/latest/namespaces/public/pr/base/bytes_splitAt/;/terms/Bytes/splitAt).

## Code review

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load unison.public.base.main ceedubs.public.pr.base.bytes_splitAt
  
  Added definitions:
  
     Bytes.splitAt.doc   : Doc (+2 metadata)
     Bytes.splitAt       : Nat -> Bytes -> (Bytes, Bytes) (+2 metadata)
     Bytes.splitAt.tests : [test.Result] (+3 metadata)

**Comment by runarorama** [comment]
Merged into main. 🌈⭐
