### ISSUE TITLE
Rename test.random

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#148]
As of now, the `test.random` function seems to be the most ergonomic way to write tests in Unison. It has a few quirks, but they should be resolved by #147. After #147 is merged, I think that we should steer people toward writing tests with this function. But the name doesn't convey that it's good for general purpose testing (even if you don't need to use `Random`), so I think that we should rename it. Unfortunately there are a variety of test functions in base (of varying levels of user-friendliness) that take up most of the good names.

So let the name bikeshedding begin!

To me the most obvious name would probably be `test.check`, but that's already taken. Should we rename that one?

The only name I could think of that isn't taken is `test.allege` which is kind of cute but not particularly discoverable (especially if English isn't your primary language).

**Comment by ceedubs** [comment]
@rlmark would you like to weigh in on this one?

**Comment by runarorama** [comment]
I've done the following renames:

1. `ensure'` -> `ensureWith`
2. `random` -> `verify`
3. `randomWithSeed` -> `verifyWithSeed`
4. `validate` -> `ensuring`

The idea with 4 is that it's basically like `ensure`, but takes a thunk, so you might say `ensuring do ...`
