### ISSUE TITLE
Add data.Set.isEmpty and doc

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#149]
You can see it on Share [here](https://share.unison-lang.org/@ceedubs/p/code/latest/namespaces/public/pr/base/set_is_empty/;/terms/data/Set/isEmpty).

The namespace to pull is `ceedubs.public.pr.base.set_is_empty`.

**Comment by runarorama** [comment]
Love the link to Share, that's super helpful. Merged to base.
