### ISSUE TITLE
couldn't delete an M1 base because `_latest` depends on it

### ISSUE THREAD

**Issue by aryairani** [unisonweb/base#15]
@hojberg ran into this on dog-fooding day.

This works:
```
.> pull https://github.com/unisonweb/base:.releases._M1m M1m
.> delete.namespace M1m
```

But this fails, because the `.releases._M2*` namespaces are not self-contained; they're missing names for some types used by the constructors of `IO.Deprecated`.

```
.> pull https://github.com/unisonweb/base:.releases._M2g M2g
.> pull https://github.com/unisonweb/base:.releases._M1m M1m
.> delete.namespace M1m
```

`.trunk` is ok in this case, though; it includes names for them, like `io.deprecated.Error.Deprecated`

**Comment by aryairani** [comment]
This works:
```
.> pull https://github.com/unisonweb/base:.releases._M1m M1m
.> delete.namespace M1m
```

This fails:
```
.> pull https://github.com/unisonweb/base:.releases._M2g M2g
.> pull https://github.com/unisonweb/base:.releases._M1m M1m
.> delete.namespace M1m
```

**Comment by runarorama** [comment]
This will be fixed by just making a release from trunk.
