### ISSUE TITLE
hmac and hmacBytes docs seem a bit off

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#150]
The `hmacBytes` doc examples use `hmac` instead of `hmacBytes`.

Also the `hmac` doc examples convert the message to `Bytes` via `toUtf8` when they don't necessarily need to, since `hmac` takes an arbitrary type of message.

**Comment by runarorama** [comment]
I've updated these docs. I also added the following note:

    | ‼️
    |
    | This function hashes a Unison-specific byte encoding of the message. If you
    | want fine control over how the message is encoded, first convert it to Bytes
    | and then use hmacBytes instead. See the documentation of hmacBytes for
    | details.
