### ISSUE TITLE
Add effectful versions of List.fill and Ask.provide

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#152]
I'm not sure of the best names for these, but I think that they are useful.

You can see them on Share:

- [Ask.provide'](https://share.unison-lang.org/@ceedubs/p/code/latest/namespaces/public/pr/base/lazy_provide/;/terms/abilities/Ask/provide')
- [List.fill'](https://share.unison-lang.org/@ceedubs/p/code/latest/namespaces/public/pr/base/lazy_provide/;/terms/data/List/fill')

## Code review

```
  ⍟ I've added these definitions:
  
    abilities.Ask.provide'         : '{g} a -> '{g, Ask a} r ->{g} r
    abilities.Ask.provide'.doc     : Doc
    abilities.Ask.provide'.handler : '{g} a -> abilities.Request {Ask a} r ->{g} r
    abilities.Ask.provide'.tests   : [test.Result]
    data.List.fill'                : Nat -> '{g} a ->{g} [a]
    data.List.fill'.doc            : Doc
    data.List.fill'.tests          : [test.Result]
```

**Comment by runarorama** [comment]
This is now in `base/main`. Thanks! 🌈⭐
