### ISSUE TITLE
Add Ask.toStore

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#154]
This converts `Ask.ask` to `Store.get`. You can see it on Share [here](https://share.unison-lang.org/@ceedubs/p/code/latest/namespaces/public/pr/base/ask_to_store/;/terms/abilities/Ask/toStore).

## Code review

```
  ⍟ I've added these definitions:
  
    abilities.Ask.toStore         : '{g, Ask a} r ->{g, Store a} r
    abilities.Ask.toStore.doc     : Doc
    abilities.Ask.toStore.handler : abilities.Request {Ask a} r ->{Store a} r
    abilities.Ask.toStore.tests   : [test.Result]
```

**Comment by runarorama** [comment]
Merged to main. 🌈⭐
