### ISSUE TITLE
TlsSocket.close doesn't close the socket

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#157]
`TlsSocket.close` says that it closes the TLS socket. However, it just calls `Tls.terminate.impl`. The docs for `Tls.terminate` (which also just wraps `Tls.terminate.impl` state that it does _not_ close the socket.

So either `TlsSocket.close` should be renamed to `TlsSocket.terminate` or it should call both `terminate` _and_ `close`.

<img width="767" alt="Screenshot 2023-05-15 at 9 47 52 PM" src="https://github.com/unisonweb/base/assets/977929/46e55ea5-dcbd-46db-89da-8fbbf6bab420">

**Comment by runarorama** [comment]
I changed this doc in `main`

**Comment by ceedubs** [comment]
Thank you @runarorama! It looks like you also renamed it to `TlsSocket.terminate`.

**Comment by pchiusano** [comment]
@runarorama can you also add `TlsSocket.close`? Seems like both `terminate` and `close` are useful.
