### ISSUE TITLE
MVar/TVar documentation/tweaks

### ISSUE THREAD

**Issue by dolio** [unisonweb/base#16]
The changes summarized below are available for you to review, using the
  following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/dolio/unison-base-contrib:.work.doc.concurrency

  Updates:

     io.MVar.tryPut : MVar a -> a ->{IO} Either Failure Boolean
     ↓
     io.MVar.tryPut : MVar a -> a ->{IO, Exception} Boolean
     +  unisoncomputing2021 : License
     +  dolio               : Author

     io.MVar.tryRead : MVar a ->{IO} Either Failure (Optional a)
     ↓
     io.MVar.tryRead : MVar a ->{IO, Exception} Optional a
     +  unisoncomputing2021 : License
     +  dolio               : Author

  Added definitions:

     io.MVar.isEmpty.doc  : Doc (+2 metadata)
     io.MVar.new.doc      : Doc (+2 metadata)
     io.MVar.newEmpty.doc : Doc (+2 metadata)
     io.MVar.put.doc      : Doc (+2 metadata)
     io.MVar.read.doc     : Doc (+2 metadata)
     io.MVar.swap.doc     : Doc (+2 metadata)
     io.MVar.take.doc     : Doc (+2 metadata)
     io.MVar.tryPut.doc   : Doc (+2 metadata)
     io.MVar.tryRead.doc  : Doc (+2 metadata)
     io.MVar.tryTake.doc  : Doc (+2 metadata)
     io.TVar.modify       : TVar a -> (a ->{STM} a) ->{STM} () (+2 metadata)
     io.TVar.modify.doc   : Doc (+2 metadata)
     io.TVar.new.doc      : Doc (+2 metadata)
     io.TVar.newIO.doc    : Doc (+2 metadata)
     io.TVar.read.doc     : Doc (+2 metadata)
     io.TVar.readIO.doc   : Doc (+2 metadata)
     io.TVar.state        : TVar s
                          -> (s ->{e} (a, s))
                          ->{e, STM} a (+2 metadata)
     io.TVar.state.doc    : Doc (+2 metadata)
     io.TVar.swap.doc     : Doc (+2 metadata)
     io.TVar.write.doc    : Doc (+2 metadata)

  Name changes:

    Original            Changes
     io.MVar.tryPut      io.MVar.tryPut.impl (added)
                         io.MVar.tryPut (removed)

     io.MVar.tryRead     io.MVar.tryRead.impl (added)
                         io.MVar.tryRead (removed)

**Comment by dolio** [comment]
In addition to the doc work, I noticed that `tryPut` and `tryRead` on `MVar` were the raw `Either` versions, so I moved them and wrapped them in the `Exception` ability.

**Comment by dolio** [comment]
I pushed some additional docs for `MVar` `TVar` `STM` and a couple other related functions. Hopefully the PR still works.

**Comment by runarorama** [comment]
Merged in into base in root hash #qua5u4r2gb
