### ISSUE TITLE
Revamp `TlsSocket` API

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#160]
`TlsSocket` will pick up an additional argument, the underlying `Socket`.

`TlsSocket.close` will then `terminate` the underlying `Tls` and `close` the `Socket`.

@stew also suggested that `TlsSocket.create` could just do the handshaking: 

> or TlsSocket create function could just take HostName and Port instead of Socket, and just rename terminate to close

[convo in Slack](https://unisonlanguage.slack.com/archives/C0131N9QPV1/p1684201871680119)

**Comment by runarorama** [comment]
With the existence of https://share.unison-lang.org/@runarorama/tls-simple, snoozing this for now.
