### ISSUE TITLE
Remove installation command from README

### ISSUE THREAD

**Issue by Adrien-LUDWIG** [unisonweb/base#161]
Hi,

While installing Unison, I launched the UCM but it did not download the `base` library as stated in [the quickstart](https://www.unison-lang.org/learn/quickstart/#step-2-create-your-unison-codebase), probably because I had no internet connexion at that time. When I relaunched the UCM later, nothing happened. So, I started to look for a way to download the `base` library. I ended up on this repository. As I was too exited to start my Unsion journey, I did not read about the deprecation part and went directly to the installation. 

The installation command, here:

https://github.com/unisonweb/base/blob/b4c31a37bcd92f9bcaddbbc0d0f47502f2cf74e9/README.md?plain=1#L14

Gave me this error:

```
.> pull https://github.com/unisonweb/base:v3:.releases._latest .base                     

  Downloaded 0 entities...


  ❗️
  
  The server sent a response that we couldn't decode: Error in $: Unexpected GetCausalHashByPathResponse type: user_not_found

  Downloaded 0 entities.
```

It worked well when I used: 

```
pull unison.public.base.latest .base
```

Maybe the installation command in the REAMDE should be removed ? 
And the deprecation note be more "eye catchy" ?

**Comment by runarorama** [comment]
Thanks for reporting. Those instructions are gone now.
