### ISSUE TITLE
networkAccess doc: Tls.terminate mentioned twice.

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#162]
The `networkAccess` doc mentioned `Tls.terminate` twice. I think that maybe one of these is suppose to mention `Socket.close`?

```
When you're done with the socket, you should close it withTlsSocket.terminate:

TlsSocket.terminate : TlsSocket ->{IO, Exception} ()

For TLS versions before 1.2, it's important to callTls.terminatebefore closing the socket.

Tls.terminate : Tls ->{IO, Exception} ()
```

**Comment by runarorama** [comment]
This seems already fixed by recent changes to TLS functions.

**Comment by ceedubs** [comment]
👍 yep this is fixed in main, but as far as I can tell hasn't yet made it into a release.
