### ISSUE TITLE
minor: evalToText error message says Debug.toText

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#168]
```
evalToText : a -> Text
evalToText a =
  match evalToText.impl a with
    None ->
      "⚠️ (Debug.toText called, but Unison is not being run with tracing support)"
    Some e -> Either.fold id id e
```

The `Debug.toText` should be `Debug.evalToText`.

Side note: it would be cool if we could use term links in a reliable way for this sort of thing.

**Comment by pchiusano** [comment]
How come this was renamed? The `eval` part doesn't mean anything to me. Also feel like this belongs under the `Debug` namespace along with `Debug.trace`.

**Comment by pchiusano** [comment]
Also, in general, don't think we should change this function's implementation based on whatever its current name is, that's needless churn and this message will rarely if ever show up.
