### ISSUE TITLE
Add base.Text.join for joining lists of Text with a separator

### ISSUE THREAD

**Issue by hojberg** [unisonweb/base#17]
## Overview
Add a simple `join` function to take a list of Text and a separator and join the list on that separate.

```
Text.join ", " ["Hello", "World"] -- "Hello, World"
```

## Code review

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/hojberg/unison-base:._prs.base

  Added definitions:

     Text.join           : Text -> [Text] -> Text (+2 metadata)
     Text.join.doc       : Doc (+2 metadata)
     Text.join.tests.ex1 : [Result] (+3 metadata)

**Comment by runarorama** [comment]
This PR is slightly incomplete. It's missing a name for the author metadata hash. It's not really a problem though, as you can always submit that name in a later PR.

**Comment by runarorama** [comment]
Merged into base in root hash #dolohrbfdd. 🌈⭐
