### ISSUE TITLE
Implemented `TMVar` and associated functions

### ISSUE THREAD

**Issue by dolio** [unisonweb/base#18]
The changes summarized below are available for you to review, using the
  following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.
com/dolio/unison-base-contrib:.work.tmvar

  Added definitions:

     type io.TMVar a (+2 metadata)
     io.TMVar.TMVar          : TVar (Optional a) -> TMVar a
     io.TMVar.doc            : Doc (+2 metadata)
     io.TMVar.isEmpty        : TMVar a ->{STM} Boolean (+2 metadata)
     io.TMVar.isEmpty.doc    : Doc (+2 metadata)
     io.TMVar.new            : a ->{STM} TMVar a (+2 metadata)
     io.TMVar.new.doc        : Doc (+2 metadata)
     io.TMVar.newEmpty       : '{STM} TMVar a (+2 metadata)
     io.TMVar.newEmpty.doc   : Doc (+2 metadata)
     io.TMVar.newEmptyIO     : '{IO} TMVar a (+2 metadata)
     io.TMVar.newEmptyIO.doc : Doc (+2 metadata)
     io.TMVar.newIO          : a ->{IO} TMVar a (+2 metadata)
     io.TMVar.newIO.doc      : Doc (+2 metadata)
     io.TMVar.put            : TMVar a -> a ->{STM} () (+2 metadata)
     io.TMVar.put.doc        : Doc (+2 metadata)
     io.TMVar.read           : TMVar a ->{STM} a (+2 metadata)
     io.TMVar.read.doc       : Doc (+2 metadata)
     io.TMVar.swap           : TMVar a -> a ->{STM} a (+2 metadata)
     io.TMVar.swap.doc       : Doc (+2 metadata)
     io.TMVar.take           : TMVar a ->{STM} a (+2 metadata)
     io.TMVar.take.doc       : Doc (+2 metadata)
     io.TMVar.tryPut         : TMVar a -> a ->{STM} Boolean (+2 metadata)
     io.TMVar.tryPut.doc     : Doc (+2 metadata)
     io.TMVar.tryRead        : TMVar a ->{STM} Optional a (+2 metadata)
     io.TMVar.tryRead.doc    : Doc (+2 metadata)
     io.TMVar.tryTake        : TMVar a ->{STM} Optional a (+2 metadata)
     io.TMVar.tryTake.doc    : Doc (+2 metadata)

**Comment by runarorama** [comment]
Pushed to `trunk` in hash `#k4dtlqavv7` 🌈⭐
