### ISSUE TITLE
Duration./ truncates

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#180]
`Duration.second / +2` gives `0` rather than `+500 * millisecond`

**Comment by gfinol** [comment]
Hi,
We have been solving this issue in the Unison discord. 

I think that the issue is solved in this branch:
[@gfinol/duration-truncation](https://share.unison-lang.org/@unison/base/code/@gfinol/duration-truncation/latest)

**Comment by runarorama** [comment]
This is merged into `main`. Thank you! 🌈⭐
