### ISSUE TITLE
PR: Small performance optimization to List.slidingPairs

### ISSUE THREAD

**Issue by jskripsky** [unisonweb/base#183]
This is my first contribution to Unison base, so please bear with me.

## Changes to `List.slidingPairs`
* Use pattern matching instead of `List.take` and `List.drop`.

## Links to Unison Share
* [PR branch](https://share.unison-lang.org/@unison/base/code/@jskripsky/optimize-List-slidingPairs/latest)
* `List.slidingPairs` comparison:
  * [current version](https://share.unison-lang.org/@unison/base/code/releases/2.7.0/latest/terms/data/List/slidingPairs)
  * [modified version](https://share.unison-lang.org/@unison/base/code/@jskripsky/optimize-List-slidingPairs/latest/terms/data/List/slidingPairs)

I've added myself to `metadata.{authors, copyrightHolders}` and the MIT license to `metadata.licenses.jskripsky2023`.
Let my know if anything is missing or needs changing.

**Comment by rlmark** [comment]
🎉 Thank you for the PR @jskripsky! We're grateful for the contributions. Welcome!

**Comment by rlmark** [comment]
This has been merged into `main`. @jskripsky, I linked your author and license metadata to the `List.slidingPairs` term so you'll show up in the metadata linked to the term. You can set up your codebase to manually `link` your author and license to the things you write or contribute with a config file: https://www.unison-lang.org/learn/tooling/configuration/. Admittedly, it's a clunky process at the moment, but if you have questions you can ping one of us in the slack.

**Comment by rlmark** [comment]
Closing as merged in `/main`
