### ISSUE TITLE
PR: new function List.slidingWindow

### ISSUE THREAD

**Issue by jskripsky** [unisonweb/base#186]
This PR adds a new function `List.slidingWindow` along with docs and tests. It's a generalization of `slidingPairs`.

The F# Core libraries contain an equivalent function [`List.windowed`](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-listmodule.html#windowed) which I've found quite useful.

[Here](https://share.unison-lang.org/@unison/base/code/@jskripsky/list-slidingWindows) is the PR branch.
[Here](https://share.unison-lang.org/@unison/base/code/@jskripsky/list-slidingWindows/latest/terms/data/List/slidingWindow)  is the direct link to the function.

**Comment by runarorama** [comment]
Merged to `main`. More! 🌈⭐
