### ISSUE TITLE
Add `Text.cons` (and tests for `Text.uncons`)

### ISSUE THREAD

**Issue by JohanWinther** [unisonweb/base#188]
# Comments
This is my first PR to the Unison Base library.
It was a bit confusing to get the metadata correctly set up, but they should be properly linked to all new additions. Also the workflow for submitting a PR was a bit misleading when using projects, but I managed to figure out what to do by looking at the other recently closed PRs in the repo.

# Changes
The branch https://share.unison-lang.org/@unison/base/code/@johanwinther/text-cons/latest adds
1. [`Text.cons`](https://share.unison-lang.org/@unison/base/code/@johanwinther/text-cons/latest/terms/Text/cons) (like [`Text.uncons`](https://share.unison-lang.org/@unison/base/code/@johanwinther/text-cons/latest/terms/Text/uncons) but reversed)
2. [`Text.cons.tests`](https://share.unison-lang.org/@unison/base/code/@johanwinther/text-cons/latest/terms/Text/cons/tests)
3. [`Text.uncons.tests`](https://share.unison-lang.org/@unison/base/code/@johanwinther/text-cons/latest/terms/Text/uncons/tests)

**Comment by runarorama** [comment]
Merged into `main`. Thank you! 🌈⭐
