### ISSUE TITLE
Even more List performance improvements

### ISSUE THREAD

**Issue by jskripsky** [unisonweb/base#189]
This PR optimizes yet more List functions. The branch is [here](https://share.unison-lang.org/@unison/base/code/@jskripsky/even-more-list-opts2).

Changes:
- do not use an index and `List.at` in these:
  - `List.map`
  - `List.foldRight`
  - `List.foldLeft`
  - `List.zip`
  - `List.distinct`
  - `List.distinctBy`
- do not use `Search.indexOf` in `List.contains`
- do not use `List.range` and `List.zip` in `List.indexed`
- do not use `List.flatMap` (to avoid the allocation of many tiny lists) in `filterMap`
- unroll `List.foldLeft` for this specific case in `List.mapIndexed`

# New Code
```haskell
data.List.map : (a ->{𝕖} b) -> [a] ->{𝕖} [b]
data.List.map f =
  go acc = cases
    a +: as -> go (acc :+ (f a)) as
    [] -> acc
  go []

data.List.foldRight : (a ->{𝕖} b ->{𝕖} b) -> b -> [a] ->{𝕖} b
data.List.foldRight f b =
  go b = cases
    as :+ a -> go (f a b) as
    [] -> b
  go b

data.List.foldLeft : (b ->{𝕖} a ->{𝕖} b) -> b -> [a] ->{𝕖} b
data.List.foldLeft f b =
  go b = cases
    a +: as -> go (f b a) as
    [] -> b
  go b

data.List.zip : [a] -> [b] -> [(a, b)]
data.List.zip =
  go acc as bs = match (as, bs) with
    (a +: as, b +: bs) -> go (acc :+ (a, b)) as bs
    _ -> acc
  go []

data.List.distinct : [a] -> [a]
data.List.distinct =
  go seen acc = cases
    a +: as
      | Set.contains a seen -> go seen acc as
      | otherwise -> go (Set.insert a seen) (acc List.:+ a) as
    [] -> acc
  go Set.empty []

data.List.distinctBy : (a ->{𝕖} b) -> [a] ->{𝕖} [a]
data.List.distinctBy f =
  go seen acc = cases
    a +: as ->
      b = f a
      if Set.contains b seen then go seen acc as
      else go (Set.insert b seen) (acc :+ a) as
    [] -> acc
  go Set.empty []
```

```haskell
data.List.contains : a -> [a] -> Boolean
data.List.contains a = cases
    hd +: tl
        | hd === a -> true
        | otherwise -> elem a tl
    [] -> false

data.List.indexed : [a] -> [(a, Nat)]
data.List.indexed =
    go acc i = cases
        a +: as -> go (acc List.:+ (a, i)) (i Nat.+ 1) as
        [] -> acc
    go [] 0

data.List.filterMap : (a ->{𝕖} Optional b) -> [a] ->{𝕖} [b]
data.List.filterMap f =
  go acc = cases
    a +: as ->
      b = f a
      match b with
        Some b -> go (acc :+ b) as
        None -> go acc as
    [] -> acc
  go []

data.List.mapIndexed : (Nat ->{𝕖} a ->{𝕖} b) -> [a] ->{𝕖} [b]
data.List.mapIndexed f =
  go acc i = cases
    a +: as -> go (acc :+ (f i a)) (i + 1) as
    [] -> acc
  go [] 0
```

**Comment by jskripsky** [comment]
Please wait with merging the branch. It seems to be broken due to https://github.com/unisonweb/unison/issues/4362.

**Comment by jskripsky** [comment]
I've downgraded UCM to release/M5g, where updating all functions works as expected.

The properly working PR branch is [here](https://share.unison-lang.org/@unison/base/code/@jskripsky/even-more-list-opts2).

**Comment by jskripsky** [comment]
PS: Feel free to delete all my past branches in @unison/base after merging. I can't do it myself (missing permissions?).

**Comment by runarorama** [comment]
This is merged into `main`. I did a bit of clocking and these are consistently about 50% faster than the previous implementations.

Thanks!

🌈⭐
