### ISSUE TITLE
Move `Universal.<` and friends to a new name

### ISSUE THREAD

**Issue by runarorama** [unisonweb/base#19]
This gives the `Universal.<` function (and `>` etc) the same treatment as when we moved `Universal.==` to `Universal.===`, and for the same reason. Structural comparison is almost always never the comparison you want, in particular because of things like https://github.com/unisonweb/unison/issues/2083, and having a name in common use like `<` is potentially confusing.

Introduced `Nat.<` etc. as well as `Int.<` etc.
Added some documentation to the `Universal` namespace.

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk git@github.com:runarorama/bv2:.prs.universal

  Updates:

     Universal.compareOn : (a ->{e} x) -> a -> a ->{e} Ordering
     -  base.Universal.compareOn.doc : Doc.Deprecated
     +  Universal.compareOn.doc      : Doc

     Universal.compareOn.doc : Doc.Deprecated
     ↓
     Universal.compareOn.doc : Doc
     +  unisoncomputing2021 : License
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     Universal.max : a -> a -> a
     -  base.Universal.max.doc : Doc.Deprecated
     +  Universal.max.doc      : Doc

     Universal.max.doc : Doc.Deprecated
     ↓
     Universal.max.doc : Doc
     +  unisoncomputing2021 : License
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     Universal.min : a -> a -> a
     -  base.Universal.min.doc : Doc.Deprecated
     +  Universal.min.doc      : Doc

     Universal.min.doc : Doc.Deprecated
     ↓
     Universal.min.doc : Doc
     +  unisoncomputing2021 : License
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     Universal.ordering : a -> a -> Ordering
     -  base.Universal.ordering.doc : Doc.Deprecated
     +  Universal.ordering.doc      : Doc

     Universal.ordering.doc : Doc.Deprecated
     ↓
     Universal.ordering.doc : Doc
     +  unisoncomputing2021 : License
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     patch patch (added 4 updates)

  Added definitions:

     Universal.compare.doc         : Doc (+2 metadata)
     Universal.identical.doc       : Doc (+2 metadata)
     Universal.notIdentical.doc    : Doc (+2 metadata)
     Universal.precedes.doc        : Doc (+2 metadata)
     Universal.precedesOrEqual.doc : Doc (+2 metadata)
     Universal.succeeds.doc        : Doc (+2 metadata)
     Universal.succeedsOrEqual.doc : Doc (+2 metadata)

  Removed definitions:

     Universal.ordering.doc.snippet1 : Doc.Deprecated

  Name changes:

    Original          Changes
     Float.gt          Float.> (added)

     Float.gteq        Float.>= (added)

     Float.lt          Float.< (added)

     Float.lteq        Float.<= (added)

     Int.gt            Int.> (added)

     Int.gteq          Int.>= (added)

     Int.lt            Int.< (added)

     Int.lteq          Int.<= (added)

     Nat.gt            Nat.> (added)

     Nat.gteq          Nat.>= (added)

     Nat.lt            Nat.< (added)

     Nat.lteq          Nat.<= (added)

     Set.equals        Set.== (added)

     Universal.!=      Universal.notIdentical (added)
                       Universal.!= (removed)

     Universal.<       Universal.precedes (added)
                       Universal.< (removed)

     Universal.<=      precedesOrEqual (added)
                       Universal.<= (removed)

     Universal.===     Universal.identical (added)

     Universal.>       Universal.succeeds (added)
                       Universal.> (removed)

     Universal.>=      Universal.succeedsOrEqual (added)
                       Universal.>= (removed)

**Comment by pchiusano** [comment]
@runarorama cool. 

For naming, we should probably be consistent on `lessThan` vs `lt` vs `precedes` etc. I'd go with `Universal.lt`, `Universal.gt`, `Universal.gteq` etc for consistency with what's already there for the other types.

Argument against precedes/succeeds is that "succeeds" has a confusing alternate meaning and I think "less than" / "greater than" is more common nomenclature.

Also noting that the FQN `Universal.gteq` is fewer characters than `succeedsOrEqual` :)

Also can you check the patch? Based on your description it doesn't sound like there should be any new patch entries.

Once we do https://github.com/unisonweb/unison/issues/2133 we can start adding aliases to base as we see fit.

**Comment by runarorama** [comment]
Fixed and pushed to trunk as hash `#c344nqj8u5`
