### ISSUE TITLE
main branch of this repo is too big

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#193]
Cloning this repo takes ages because of the large sqlite file (and possibly git history of files from the old codebase format?). 

Unfortunately there isn't a good way to remedy this without rewriting some git history.

My proposal would be:

1. Create a branch off of the current main (`bkp-2023-12-21` or something like that).
2. Use something like https://rtyley.github.io/bfg-repo-cleaner/ to remove the cruft from the main branch.
3. Depending on someone's git client/config they might need to use `clone --single-branch` to take advantage of this change.

**Comment by hojberg** [comment]
@ceedubs I'm confused. Hasn't this all moved to Share? Are we still using the stuff thats in this repo, or is it just for issue tracking?

**Comment by ceedubs** [comment]
Yeah, the Unison code has moved to Share. Mostly this repo is for tracking issues. But also I want to set up some CI (GitHub Actions) that pulls base and runs tests. The first step of that will be to checkout this repo, which is why I noticed that it is so big :)
