### ISSUE TITLE
Adding an unsafeRun! function for Exception

### ISSUE THREAD

**Issue by rlmark** [unisonweb/base#20]
* This PR adds a function called `Exception.unsafeRun!` which will call the `bug` built-in if an exception is raised. It's a bit of a stopover until the solution for `https://github.com/unisonweb/unison/issues/2025` lands.

## Code review
 
  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load git@github.com:unisonweb/base:.trunk.Exception git@github.com:rlmark/my-unison-repo2:.myBase.unsafeRunPr.Exception
  
  Added definitions:
  
     unsafeRun!     : '{g, Exception} a ->{g} a (+2 metadata)
     unsafeRun!.doc : Doc (+3 metadata)

**Comment by runarorama** [comment]
Merged in root hash `#sttm2ll24n`. Thank you! 🌈🌟
