### ISSUE TITLE
Stream functions

### ISSUE THREAD

**Issue by anovstrup** [unisonweb/base#21]
The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/anovstrup/unison-all:.prs.base._stream.v3

  Updates:

     Stream.range : Nat -> Nat ->{Stream Nat} ()
     ↓
     Stream.range : Nat -> Nat -> '{Stream Nat} ()
     +  anovstrup.mit_2020  : License
     +  unisoncomputing2020 : License
     +  pchiusano           : Author
     +  authors.anovstrup   : Author

     Stream.toList : '{e, Stream a} () ->{e} [a]
     ↓
     Stream.toList : '{g, Stream a} r -> '{g} [a]
     -  unisoncomputing2020 : License
     -  pchiusano           : Author
     +  anovstrup.mit_2020  : License
     +  authors.anovstrup   : Author

    There were 1 auto-propagated updates.

     patch patch (added 1 updates)

  Added definitions:

     Stream.++                        : (v1 ->{g, Stream a} v2)
                                      -> (v2 ->{g, Stream a} v3)
                                      -> v1
                                      ->{g, Stream a} v3 (+2 metadata)
     Stream.++.doc                    : _M2.Doc (+2 metadata)
     Stream.+:                        : a -> '{Stream a} r -> '{Stream a} r (+2 metadata)
     Stream.+:.doc                    : _M2.Doc (+2 metadata)
     Stream.Int.all                   : '{Stream Int} a (+2 metadata)
     Stream.Int.all.doc               : _M2.Doc (+2 metadata)
     Stream.Int.from                  : Int -> '{Stream Int} a (+2 metadata)
     Stream.Int.from!                 : Int ->{Stream Int} a (+2 metadata)
     Stream.Int.from!.doc             : _M2.Doc (+2 metadata)
     Stream.Int.from.doc              : _M2.Doc (+2 metadata)
     Stream.Int.negatives             : '{Stream Int} a (+2 metadata)
     Stream.Int.negatives.doc         : _M2.Doc (+2 metadata)
     Stream.Int.positives             : '{Stream Int} a (+2 metadata)
     Stream.Int.positives.doc         : _M2.Doc (+2 metadata)
     Stream.Int.range                 : Int -> Int -> '{Stream Int} () (+2 metadata)
     Stream.Int.range!                : Int ->{Stream Int} Int ->{Stream Int} () (+2 metadata)
     Stream.Int.range!.doc            : _M2.Doc (+2 metadata)
     Stream.Int.range.doc             : _M2.Doc (+2 metadata)
     Stream.Nat.all                   : '{Stream Nat} a (+2 metadata)
     Stream.Nat.all.doc               : _M2.Doc (+2 metadata)
     Stream.drop                      : Nat -> '{g, Stream a} r -> '{g, Stream a} r (+2 metadata)
     Stream.drop!                     : Nat -> '{g, Stream a} r ->{g, Stream a} r (+2 metadata)
     Stream.drop!.doc                 : _M2.Doc (+2 metadata)
     Stream.drop.doc                  : _M2.Doc (+2 metadata)
     Stream.drop.test                 : [Result] (+3 metadata)
     Stream.emitAndReturn             : a -> '{Stream a} a (+2 metadata)
     Stream.emitAndReturn!            : a ->{Stream a} a (+2 metadata)
     Stream.emitAndReturn!.doc        : _M2.Doc (+2 metadata)
     Stream.emitAndReturn.doc         : _M2.Doc (+2 metadata)
     Stream.filter                    : (a ->{g} Boolean)
                                      -> '{g, Stream a} r
                                      -> '{g, Stream a} r (+2 metadata)
     Stream.filter!                   : (a ->{g} Boolean)
                                      -> '{g, Stream a} r
                                      ->{g, Stream a} r (+2 metadata)
     Stream.filter!.doc               : _M2.Doc (+2 metadata)
     Stream.filter.doc                : _M2.Doc (+2 metadata)
     Stream.filter.test               : [Result] (+3 metadata)
     Stream.flatMap                   : (a ->{e, Stream a} r)
                                      -> '{e, Stream a} r
                                      -> '{e, Stream a} r (+2 metadata)
     Stream.flatMap!                  : (a ->{e, Stream b} r)
                                      -> '{e, Stream a} r
                                      ->{e, Stream b} r (+2 metadata)
     Stream.flatMap!.doc              : _M2.Doc (+2 metadata)
     Stream.flatMap.doc               : _M2.Doc (+2 metadata)
     Stream.flatMap.test              : [Result] (+3 metadata)
     Stream.fold                      : (b ->{g} a ->{g} b)
                                      -> b
                                      -> '{g, Stream a} r
                                      -> '{g} b (+2 metadata)
     Stream.fold!                     : (b ->{g} a ->{g} b)
                                      -> b
                                      -> '{g, Stream a} r
                                      ->{g} b (+2 metadata)
     Stream.fold!.doc                 : _M2.Doc (+2 metadata)
     Stream.fold!.test                : [Result] (+3 metadata)
     Stream.fold.doc                  : _M2.Doc (+2 metadata)
     Stream.foldWithResult            : (b ->{g} a ->{g} b)
                                      -> b
                                      -> '{g, Stream a} r
                                      -> '{g} (b, r) (+2 metadata)
     Stream.foldWithResult!           : (b ->{g} a ->{g} b)
                                      -> b
                                      -> '{g, Stream a} r
                                      ->{g} (b, r) (+2 metadata)
     Stream.foldWithResult!.doc       : _M2.Doc (+2 metadata)
     Stream.foldWithResult!.handler   : (b ->{g} a ->{g} b)
                                      -> b
                                      -> Request (Stream a) r
                                      ->{g} (b, r) (+2 metadata)
     Stream.foldWithResult!.test      : [Result] (+3 metadata)
     Stream.foldWithResult.doc        : _M2.Doc (+2 metadata)
     Stream.from                      : Nat -> '{Stream Nat} a (+2 metadata)
     Stream.from!                     : Nat ->{Stream Nat} a (+2 metadata)
     Stream.from!.doc                 : _M2.Doc (+2 metadata)
     Stream.from.doc                  : _M2.Doc (+2 metadata)
     Stream.fromList                  : [a] -> '{Stream a} () (+2 metadata)
     Stream.fromList!                 : [a] ->{Stream a} () (+2 metadata)
     Stream.fromList!.doc             : _M2.Doc (+2 metadata)
     Stream.fromList.doc              : _M2.Doc (+2 metadata)
     Stream.interleave                : '{g, Stream a} r
                                      -> '{g, Stream a} r
                                      -> '{g, Stream a} r (+2 metadata)
     Stream.interleave!               : '{g, Stream a} r
                                      -> '{g, Stream a} r
                                      ->{g, Stream a} r (+2 metadata)
     Stream.interleave!.doc           : _M2.Doc (+2 metadata)
     Stream.interleave!.handler       : '{e} r
                                      -> Request (Stream a) r
                                      ->{e, Stream a} r (+2 metadata)
     Stream.interleave.doc            : _M2.Doc (+2 metadata)
     Stream.map                       : (a ->{g} b)
                                      -> '{g, Stream a} r
                                      -> '{g, Stream b} r (+2 metadata)
     Stream.map!                      : (a ->{g} b)
                                      -> '{g, Stream a} r
                                      ->{g, Stream b} r (+2 metadata)
     Stream.map!.doc                  : _M2.Doc (+2 metadata)
     Stream.map.doc                   : _M2.Doc (+2 metadata)
     Stream.map.test                  : [Result] (+3 metadata)
     Stream.pipe                      : '{g, Stream a} r
                                      -> '{g, Stream b, Ask a} r
                                      -> '{g, Stream b} r (+2 metadata)
     Stream.pipe!                     : '{g, Stream a} r
                                      -> '{g, Stream b, Ask a} r
                                      ->{g, Stream b} r (+2 metadata)
     Stream.pipe!.doc                 : _M2.Doc (+2 metadata)
     Stream.pipe!.handler             : '{g, Stream a} r
                                      -> Request {Ask a, Stream b} r
                                      ->{g, Stream b} r (+2 metadata)
     Stream.pipe.doc                  : _M2.Doc (+2 metadata)
     Stream.range!.doc                : _M2.Doc (+2 metadata)
     Stream.range.doc                 : _M2.Doc (+2 metadata)
     Stream.range.test.emptyRange     : [Result] (+3 metadata)
     Stream.range.test.emptyRange2    : [Result] (+3 metadata)
     Stream.range.test.listLike       : [Result] (+3 metadata)
     Stream.range.test.singletonRange : [Result] (+3 metadata)
     Stream.rangeClosed               : Nat -> Nat -> '{Stream Nat} () (+2 metadata)
     Stream.rangeClosed!              : Nat -> Nat ->{Stream Nat} () (+2 metadata)
     Stream.rangeClosed!.doc          : _M2.Doc (+2 metadata)
     Stream.rangeClosed.doc           : _M2.Doc (+2 metadata)
     Stream.scan                      : (b ->{g} a ->{g} b)
                                      -> b
                                      -> '{g, Stream a} r
                                      -> '{g, Stream b} r (+2 metadata)
     Stream.scan!                     : (b ->{g} a ->{g} b)
                                      -> b
                                      -> '{g, Stream a} r
                                      ->{g, Stream b} r (+2 metadata)
     Stream.scan!.doc                 : _M2.Doc (+2 metadata)
     Stream.scan.doc                  : _M2.Doc (+2 metadata)
     Stream.take                      : Nat
                                      -> '{g, Stream a} r
                                      -> '{g, Stream a} Optional r (+2 metadata)
     Stream.take!                     : Nat
                                      -> '{g, Stream a} r
                                      ->{g, Stream a} Optional r (+2 metadata)
     Stream.take!.doc                 : _M2.Doc (+2 metadata)
     Stream.take.doc                  : _M2.Doc (+2 metadata)
     Stream.take.testCompletion       : [Result] (+3 metadata)
     Stream.take.testEarlyTermination : [Result] (+3 metadata)
     Stream.terminated                : '{g, Stream a} r
                                      -> '{g, Stream (Optional a)} r (+2 metadata)
     Stream.terminated!               : '{g, Stream a} r ->{g, Stream (Optional a)} r (+2 metadata)
     Stream.terminated!.doc           : _M2.Doc (+2 metadata)
     Stream.terminated.doc            : _M2.Doc (+2 metadata)
     Stream.terminated.test           : [Result] (+3 metadata)
     Stream.to                        : Nat -> '{Stream Nat} () (+2 metadata)
     Stream.to!                       : Nat ->{Stream Nat} () (+2 metadata)
     Stream.to!.doc                   : _M2.Doc (+2 metadata)
     Stream.to.doc                    : _M2.Doc (+2 metadata)
     Stream.toList!                   : '{g, Stream a} r ->{g} [a] (+4 metadata)
     Stream.toList!.doc               : _M2.Doc (+2 metadata)
     Stream.toList.doc                : _M2.Doc (+2 metadata)
     Stream.toList.test.bidirectional : [Result] (+3 metadata)
     Stream.toListWithResult          : '{g, Stream a} r -> '{g} ([a], r) (+2 metadata)
     Stream.toListWithResult!         : '{g, Stream a} r ->{g} ([a], r) (+2 metadata)
     Stream.toListWithResult!.doc     : _M2.Doc (+2 metadata)
     Stream.toListWithResult.doc      : _M2.Doc (+2 metadata)
     Stream.until                     : Nat -> '{Stream Nat} () (+2 metadata)
     Stream.until!                    : Nat ->{Stream Nat} () (+2 metadata)
     Stream.until!.doc                : _M2.Doc (+2 metadata)
     Stream.until.doc                 : _M2.Doc (+2 metadata)
     Stream.zip                       : '{g, Stream a} r
                                      -> '{g, Stream b} r
                                      -> '{g, Stream (a, b)} r (+2 metadata)
     Stream.zip!                      : '{g, Stream a} r
                                      -> '{g, Stream b} r
                                      ->{g, Stream (a, b)} r (+2 metadata)
     Stream.zip!.doc                  : _M2.Doc (+2 metadata)
     Stream.zip.doc                   : _M2.Doc (+2 metadata)
     Stream.zipWith                   : (a ->{g} b ->{g} c)
                                      -> '{g, Stream a} r
                                      -> '{g, Stream b} r
                                      -> '{g, Stream c} r (+2 metadata)
     Stream.zipWith!                  : (a ->{g} b ->{g} c)
                                      -> '{g, Stream a} r
                                      -> '{g, Stream b} r
                                      ->{g, Stream c} r (+2 metadata)
     Stream.zipWith!.doc              : _M2.Doc (+2 metadata)
     Stream.zipWith.doc               : _M2.Doc (+2 metadata)

  Name changes:

    Original         Changes
     Stream.range     Stream.range! (added)
                      Stream.range (removed)

---

Older versions of the PR are still available to review using the following commands:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/anovstrup/unison-all:.prs.base._stream.v2

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/anovstrup/unison-all:.prs.base._streamPR

**Comment by pchiusano** [comment]
Sweet. @anovstrup I think @runarorama taking a look at this soon and might have more comments. One minor thing I noticed:

```
patch patch (added 1 updates)
```

I don't think there should be any updates as part of this if it's just new definitions, but was there some bugfix? If you just want to repurpose the `Stream.range` name but the old definition is still valid, you can do `update .trash` and then `delete.patch .trash` at your leisure. We're working on improving this workflow.

Alternately you could have done `rename.term Stream.range Stream.range!` and then `add` the new `Stream.range`.

You can also `delete.term-replacement Stream.range! Stream.range` and that might work.

@runarorama can clean this up during review, just keep the existing `trunk.patch`.

**Comment by anovstrup** [comment]
@pchiusano looks like something odd happened with `Stream.range!` after I merged `.base.Stream` into my `Stream` namespace and tried to resolve the conflicts. Now I see 
```
52. range              (Nat -> Nat -> '{Stream Nat} ())
53. range/             (5 definitions)
54. range!             (Nat -> Nat -> '{Stream Nat} ())
55. range!/            (1 definition)
```
in my namespace, which is certainly _not_ what I intended.

**Comment by pchiusano** [comment]
@anovstrup if there's a `Stream.range! -> Stream.range` mapping in the patch (my guess), then during patch propagation that will rewrite all instances of `Stream.range!` to be `Stream.range`.

Your best bet might be to 1) delete that entry from the patch, it'll look like -

```
#somehash -> Stream.range
```

And then `alias.term #somehash Stream.range!`. 

Then double check `view Stream.range!` to make sure it's what's expected.

Sorry for the trouble! This workflow needs work clearly. :|

**Comment by anovstrup** [comment]
@pchiusano I think I fixed it.

**Comment by anovstrup** [comment]
@pchiusano I'm wondering if the patch should have an entry for `Stream.toList`?  I renamed it `Stream.toList!` _and_ widened the argument type to take `'{g, Stream a} r` instead of just `'{g, Stream a} ()`, but all calls to the old `Stream.toList` can be replaced with calls to the new `Stream.toList` without intervention. Is that something ucm can handle, or do patches like that have to be done manually?

**Comment by pchiusano** [comment]
👍 

Mmm, yeah anytime the new type is a subtype of the old then that's safe to add to the patch and that can be applied automatically.

OTOH, the old version is still perfectly valid. I guess I'd lean toward not adding it to the patch for that reason but don't have strong feelings. We could always decide later. :)

**Comment by anovstrup** [comment]
@pchiusano I wound up using `alias.term .base.Stream.toList Stream.toList!` and `update Stream.toList!` to give it a patch entry, but you guys can always remove it from the patch before merging. I guess there's not really any reason for callers of the old definition to update to the new, equivalent one (_edit_: except, perhaps, that the old one won't have a name?).

**Comment by anovstrup** [comment]
I fixed an off-by-one and eagerness/type issue in `Stream.to!` and added `Stream.rangeClosed!`, `Stream.rangeClosed`, `Stream.until!` and `Stream.until` in a new version of the PR (at https://github.com/anovstrup/unison-all:.prs.base._stream.v2 instead of https://github.com/anovstrup/unison-all:.prs.base._streamPR, to facilitate code review / comparison).  The description above is updated to reflect the new version.

**Comment by anovstrup** [comment]
I generalized `interleave`/`interleave!` and `zip`/`zip!`, and added `zipWith`/`zipWith!` in https://github.com/anovstrup/unison-all:.prs.base._stream.v3.

**Comment by runarorama** [comment]
Merged into trunk in hash `#aip49ca6q5` 🌈🌟
