### ISSUE TITLE
Store.unfold, List.iterate, Stream.iterate

### ISSUE THREAD

**Issue by sullyj3** [unisonweb/base#26]
Also includes some changes from @anovstrup to Abort.

## Code review

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/sullyj3/myUnisonCodebase:.prs.base.unfoldStore

  Updates:

     Abort.toOptional : '{g, Abort} a ->{g} Optional a
     ↓
     Abort.toOptional : '{g, Abort} a -> '{g} Optional a
     -  unisoncomputing2020 : License
     -  pchiusano           : Author
     +  anovstrup.mit_2020  : License
     +  authors.anovstrup   : Author

    There were 27 auto-propagated updates.

     patch patch (added 3 updates)

  Added definitions:

     List.iterate.doc                     : Doc (+3 metadata)
     Stream.iterate.doc                   : Doc (+2 metadata)
     Stream.iterate!.doc                  : Doc (+2 metadata)
     Abort.toDefault.doc                  : Doc (+2 metadata)
     Abort.toDefault!.doc                 : Doc (+2 metadata)
     Abort.toOptional.doc                 : Doc (+2 metadata)
     Abort.toOptional!.doc                : Doc (+2 metadata)
     Store.unfold!.doc                    : Doc (+3 metadata)
     List.iterate.tests.ex1               : [Result] (+3 metadata)
     Stream.iterate.tests.ex1             : [Result] (+3 metadata)
     Store.unfold!.tests.ex1              : [Result] (+4 metadata)
     metadata.authors.jamessully.guid     : GUID
     Abort.toDefault!.handler             : a -> Request {Abort} a -> a (+2 metadata)
     List.iterate                         : (a ->{Abort} a) -> a -> [a] (+2 metadata)
     Stream.iterate                       : (a ->{g} a) -> a -> '{g, Stream a} () (+2 metadata)
     Stream.iterate!                      : (a ->{g} a) -> a ->{g, Stream a} () (+2 metadata)
     metadata.authors.jamessully          : Author
     metadata.copyrightHolders.jamessully : CopyrightHolder
     metadata.licenses.jamessully         : License
     Abort.toDefault                      : a -> '{g, Abort} a -> '{g} a (+2 metadata)
     Abort.toDefault!                     : a -> '{g, Abort} a ->{g} a (+2 metadata)
     Abort.toOptional!                    : '{g, Abort} a ->{g} Optional a (+4 metadata)
     Store.unfold                         : s -> '{g, Abort, Store s} r -> '{g} [r] (+3 metadata)
     Store.unfold!                        : s -> '{g, Abort, Store s} r ->{g} [r] (+4 metadata)

     patch Store.patch (added 2 updates)

  Removed definitions:

     Abort.toOptional.handler : Request {Abort} a -> Optional a

**Comment by pchiusano** [comment]
Cool! I probably won't get to take a closer look at this until next week and @runarorama is also out. 

One thing I noticed: I don't think there should be any patch updates with this PR. The name `Abort.toOptional` was repurposed but the old definition is still valid, and I think the definition is now called `Abort.toOptional!`. Me or @runarorama can fix up the PR though, the functionality looks great!

The workflow for this needs improvement and is being tracked here https://github.com/unisonweb/unison/issues/2248 since it's pretty error prone. One tip is you can do `update .trash` to send updates to a dummy patch that you delete occasionally.

https://www.unisonweb.org/2020/04/10/reducing-churn/ is a good post for more reading on this.

Here's another `List` function we noticed was missing that would be a good addition, if you want to take a crack at it!

```
List.find : (a ->{g} Boolean) -> [a] ->{g} Optional a
List.find! : (a ->{g} Boolean) -> [a] ->{g, Abort} a
```

**Comment by sullyj3** [comment]
Having thought about it more, I think iterate ought to return a stream, not a list, and should not require the passed function to decide when to stop. That should be the responsibility of the caller, using something like take or takewhile. In Haskell iterate returns a lazy infinite list, and I was confused since Haskell collapses the distinction between the two.

This only really occurred to me when I started coming up with examples and the passed functions were always something like

`if n > 10 then abort else n + 1` 

Which is extremely not composable.

I'm not sure whether unfold ought to as well, as in this case the provided function is supposed to be responsible for stopping, and the output will often in fact be finite. I guess it can't hurt to have both versions of both functions? Thoughts?

**Comment by sullyj3** [comment]
> Here's another List function we noticed was missing that would be a good addition, if you want to take a crack at it!

For sure, I also have `List.deleteFirst : (a -> Boolean) -> [a] -> [a]`, which I could generalize and add

**Comment by anovstrup** [comment]
@sullyj3 You'll also want to add aliases for your `Author` and `License` metadata to the `metadata.authors` and `metadata.licenses` namespaces, respectively. e.g., `alias.term sullyj3 .prs.base.unfoldStore.metadata.authors.sullyj`.

**Comment by sullyj3** [comment]
Ah yep, do I also need to alias my `CopyrightHolder` and `GUID`?

**Comment by sullyj3** [comment]
Updated with just `Author` and `License` for now

**Comment by anovstrup** [comment]
> Ah yep, do I also need to alias my `CopyrightHolder` and `GUID`?

Yep, mirror the structure of one of the existing authors. I think it's just a couple `copy.namespace` commands at this point.

**Comment by sullyj3** [comment]
Righto cool. Updated with the additional metadata as well as `Stream.iterate`

**Comment by runarorama** [comment]
Merged in base hash `#p47o3ehssr` 🌈🌟
