### ISSUE TITLE
Add List.find, List.deleteFirst

### ISSUE THREAD

**Issue by sullyj3** [unisonweb/base#29]
Add functions for finding an item in a list by predicate, and for deleting a single item from a list by predicate. Paul asked specifically for `find`, I'm happy to bikeshed or remove `deleteFirst` if y'all prefer.
<hr>

Before submitting a pull request, please doublecheck that you have included

* a clear PR description (don't bother to include issues numbers).
* `Doc`s linked for types and terms as needed
* `Author` and `License` metadata linked
* `Test`s, where appropriate

## Code review

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/sullyj3/myUnisonCodebase:.prs.base.listFind

  Added definitions:

     List.deleteFirst                     : (a ->{g} Boolean) -> [a] ->{g} [a] (+2 metadata)
     List.deleteFirst.doc                 : Doc (+2 metadata)
     List.find.doc                        : Doc (+2 metadata)
     List.find!.doc                       : Doc (+2 metadata)
     List.deleteFirst.tests.ex1           : [Result] (+4 metadata)
     List.find.tests.ex1                  : [Result] (+3 metadata)
     List.deleteFirst.tests.ex2           : [Result] (+4 metadata)
     List.find.tests.ex2                  : [Result] (+3 metadata)
     List.deleteFirst.tests.ex3           : [Result] (+4 metadata)
     List.find                            : (a ->{g} Boolean) -> [a] ->{g} Optional a (+2 metadata)
     List.find!                           : (a ->{g} Boolean) -> [a] ->{g, Abort} a (+2 metadata)
     metadata.authors.jamessully.guid     : GUID
     metadata.authors.jamessully          : Author
     metadata.copyrightHolders.jamessully : CopyrightHolder
     metadata.licenses.jamessully         : License

**Comment by pchiusano** [comment]
Thanks! Looks good, merged in #uvabu72dbc

I merged it as is, but for the docs, I'd try to include 1-2 examples to demonstrate usage. Like check out these docs:

https://share.unison-lang.org/@bspt8cr08m0m9egkb94vlalqspkudj8363knhg7llrjoblmboa0990l5otfiljnk3md0fpi2c6462qmn7iedsjd8ckggfrk4cm5tk08/terms/base/Random/doc

And you can also see the source of the doc there.
