### ISSUE TITLE
Update a number of out-of-date docs

### ISSUE THREAD

**Issue by runarorama** [unisonweb/base#32]
This updates a few terms in `base` that were referencing hashes for which there exist no names in `base`. Looks like these were artifacts of an update that didn't propagate to docs for some reason.

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk git@github.com:runarorama/bv2:.missingNamesAug11

  Updates:

     List.splitAt : Nat -> [a] -> ([a], [a])
     -  #p28531jkth : builtin.Doc
     +  splitAt.doc : builtin.Doc

     Random.boolean.doc : base.Doc
     ↓
     Random.boolean.doc : base.Doc
     +  unisoncomputing2021 : License
     +  pchiusano           : Author

     Random.doc : base.Doc
     ↓
     Random.doc : base.Doc
     +  unisoncomputing2021 : License
     +  pchiusano           : Author
     +  runarorama          : Author

     Random.lcg.doc : base.Doc
     ↓
     Random.lcg.doc : base.Doc
     +  unisoncomputing2021 : License
     +  pchiusano           : Author
     +  runarorama          : Author

     Random.natIn.doc : base.Doc
     ↓
     Random.natIn.doc : base.Doc
     +  unisoncomputing2021 : License
     +  pchiusano           : Author
     +  runarorama          : Author

     Random.natIn.tests.ex1 : [Result]
     ↓
     Random.natIn.tests.ex1 : [Result]
     +  unisoncomputing2021 : License
     +  pchiusano           : Author
     +  isTest              : IsTest
     +  runarorama          : Author

     Random.split.doc : base.Doc
     ↓
     Random.split.doc : base.Doc
     +  unisoncomputing2021 : License
     +  pchiusano           : Author
     +  runarorama          : Author

     Random.splitmix.doc : base.Doc
     ↓
     Random.splitmix.doc : base.Doc
     +  unisoncomputing2021 : License
     +  pchiusano           : Author
     +  runarorama          : Author

    There were 4 auto-propagated updates.

     patch patch (added 9 updates)

**Comment by pchiusano** [comment]
Merged in https://github.com/unisonweb/base/commit/1cad66273e910302665fbff5d215a0fe975cc1f3
