### ISSUE TITLE
Concurrent queue implementation

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#33]
Pretty standard STM-based concurrent mutable queue implementation.

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base:.trunk.io.STM https://github.com/pchiusano/unisoncode:.prs.tq
  
  Added definitions:
  
     unique type TQueue a (+2 metadata)
     TQueue.TQueue                   : TVar [a] -> TVar Nat -> TQueue a
     docs.glossary.FIFO              : Doc (+2 metadata)
     TQueue.boundedEnqueue           : Nat -> a -> TQueue a ->{STM} () (+2 metadata)
     docs.glossary.FIFO.content      : Doc (+2 metadata)
     TQueue.dequeue                  : TQueue a ->{STM} a (+2 metadata)
     TQueue.dequeueNonce             : TQueue a ->{STM} Nat (+2 metadata)
     TQueue.doc                      : Doc (+2 metadata)
     TQueue.boundedEnqueue.doc       : Doc (+2 metadata)
     TQueue.dequeue.doc              : Doc (+2 metadata)
     TQueue.dequeueNonce.doc         : Doc (+2 metadata)
     TQueue.elements.doc             : Doc (+2 metadata)
     TQueue.empty.doc                : Doc (+2 metadata)
     TQueue.enqueue.doc              : Doc (+2 metadata)
     TQueue.enqueueAll.doc           : Doc (+2 metadata)
     TQueue.fromList.doc             : Doc (+2 metadata)
     TQueue.peek.doc                 : Doc (+2 metadata)
     TQueue.pushback.doc             : Doc (+2 metadata)
     TQueue.size.doc                 : Doc (+2 metadata)
     TQueue.tryBoundedEnqueue.doc    : Doc (+2 metadata)
     TQueue.tryBoundedEnqueueAll.doc : Doc (+2 metadata)
     TQueue.tryPeek.doc              : Doc (+2 metadata)
     TQueue.elements                 : TQueue a ->{STM} [a] (+2 metadata)
     TQueue.empty                    : '{STM} TQueue a (+2 metadata)
     TQueue.enqueue                  : a -> TQueue a ->{STM} () (+2 metadata)
     TQueue.enqueueAll               : [a] -> TQueue a ->{STM} () (+2 metadata)
     TQueue.fromList                 : [a] ->{STM} TQueue a (+2 metadata)
     TQueue.peek                     : TQueue a ->{STM} a (+2 metadata)
     TQueue.pushback                 : a -> TQueue a ->{STM} () (+2 metadata)
     TQueue.size                     : TQueue a ->{STM} Nat (+2 metadata)
     TQueue.tryBoundedEnqueue        : Nat -> a -> TQueue a ->{STM} Boolean (+2 metadata)
     TQueue.tryBoundedEnqueueAll     : Nat -> [a] -> TQueue a ->{STM} Boolean (+2 metadata)
     TQueue.tryDequeue               : TQueue a ->{STM} Optional a (+2 metadata)
     TQueue.tryPeek                  : TQueue a ->{STM} Optional a (+2 metadata)

**Comment by pchiusano** [comment]
Added some basic tests as well. 

Also credit to @dolio for helping with this.

**Comment by runarorama** [comment]
Merged in base hash `#iup5vf5bqf`

🌈🌟
