### ISSUE TITLE
`unsafeAt` should use `bug` rather than infinite loop

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#34]
Currently if the index is out of bounds, it infinite loops! Ha. I think the origin of this is that it predates the `bug` function, and we had no other way to just crash the program.

https://share.unison-lang.org/@hcmfjhke0cuv26ksu80rivcmrkng2loo992j5lfogp4t8om6nu5c915064iuem8r8rsbeckopr3hmtrsqda0hiup9725h5c7req4vv8/terms/base/List/unsafeAt

**Comment by runarorama** [comment]
Fixed in base root hash `#u7lvivgp36`

Updated:

    1.  List.unsafeAt : Nat -> [a] -> a
        ↓
    2.  List.unsafeAt : Nat -> [a] -> a
        + 3.  unisoncomputing2021 : License
        + 4.  runarorama          : Author

    There were 92 auto-propagated updates.

    5.  patch patch (added 1 updates)

  Added definitions:

    6.  List.at!                              : Nat -> [a] ->{Abort} a (+2 metadata)
    7.  List.at.doc                           : Doc (+2 metadata)
    8.  List.at!.doc                          : Doc (+2 metadata)
    9.  List.unsafeAt.doc                     : Doc (+2 metadata)
    10. List.at.tests.index                   : [Result] (+3 metadata)
