### ISSUE TITLE
Missing documentation for Float.floor and Float.truncate

### ISSUE THREAD

**Issue by aryairani** [unisonweb/base#36]
Thanks to @meijeru for reporting.

**Comment by runarorama** [comment]
Fixed in base root hash `#sebqap5tcl`.

`floor` now returns a `Float` instead of an `Int`:

>  `floor x` rounds `x` down to the nearest whole number. That is, it returns the largest whole
>  number that is at most `x`.
>
>      floor 0.1
>      ⧨
>      0.0
>
>      floor -9.9
>      ⧨
>      -10.0

As does `truncate`:

>  `truncate x` returns the whole number obtained by dropping any fractional portion of `x`. That
>  is, it truncates any digits after the decimal point.
>
>      truncate 4.1
>      ⧨
>      4.0
>
>      truncate 4.9
>      ⧨
>      4.0

What used to be called `truncate` is now `unsafeToInt : Float -> Int`:

>   Converts a Float to an Int by dropping any fractional amount.
>
>       unsafeToInt 4.9
>       ⧨
>       +4
> 
>       unsafeToInt 4.1
>       ⧨
>       +4
> 
>     | ⚠️
>     |
>     | If the Float is `NaN` or outside the range of Int, this function returns `+0`:
>     |
>     |     unsafeToInt maxFloat
>     |     ⧨
>     |     +0
>
