### ISSUE TITLE
Inconsistent existence of operators across different base types

### ISSUE THREAD

**Issue by aryairani** [unisonweb/base#38]
> I have checked the definition of comparison operators for the various types. The parallelism between operators like `>` and prefix functions like `gt` is incomplete: `Universal` has `neq` but not `!=`, and `Text` has `!=` but not `neq`, nor any of `<` `<=` `>` `>=`. Both `neq` and `!=` are lacking for `Nat`, `Int` and `Float`. `Char` and `Boolean` only have `==`. `Bytes`, `List` and `Tuple` have no comparison operators defined at all. Otoh, `==` is defined for `Bag`, `Map` and `Set`.  Are there plans to make this more consistent?

Thanks to @meijeru for reporting.

**Comment by runarorama** [comment]
I've added all of these for the primitive types, but it's not really clear what the correct thing to do is with regard to comparison on collections and tuples. Needs design.
