### ISSUE TITLE
Convert from Doc.Deprecated to Doc

### ISSUE THREAD

**Issue by runarorama** [unisonweb/base#39]
There's currently not a good way of converting from the old documentation format to the new. This should be straightforward to address with a function of type `Doc.Deprecated -> Doc`.

**Comment by atacratic** [comment]
I guess that even so, in the longer term it would still be good to change the implementation of all the docs so that instead of looking like
```
blah.doc = convert [: blah! :]
```
they instead look like
```
blah.doc = {{ blah! }}
```
right?  Particularly if the pretty-print for [: :] docs has rotted?
