### ISSUE TITLE
Add names for old IO types

### ISSUE THREAD

**Issue by runarorama** [unisonweb/base#4]
This adds a `Deprecated` names for old datatypes used in `IO.Deprecated`, so that they show up with e.g. `Handle.Deprecated` rather than just hashes.

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk git@github.com:runarorama/bv2:.prs.oldio

  Added definitions:

     unique type io.deprecated.BufferMode.Deprecated
     type io.deprecated.Error.Deprecated
     unique type io.deprecated.ErrorType.Deprecated
     unique type io.deprecated.FilePath.Deprecated
     unique type io.deprecated.Handle.Deprecated
     unique type io.deprecated.HostName.Deprecated
     type io.deprecated.Mode.Deprecated
     unique type io.deprecated.SeekMode.Deprecated
     unique type io.deprecated.ServiceName.Deprecated
     unique type io.deprecated.Socket.Deprecated
     unique type io.deprecated.ThreadId.Deprecated

**Comment by runarorama** [comment]
Did this get merged or just closed?

**Comment by pchiusano** [comment]
@runarorama I think I closed this by accident! I think. If so my bad. I don't have any memory of doing so though...

**Comment by pchiusano** [comment]
This is pushed to trunk in #i6osdf384m

We noticed some weirdness with the PR reintroducing some old definitions. We weren't sure if there's some issue with LCA calculation, an issue with the diff, or if maybe the PR was prepared with an old version of Unison.

If we continue to encounter weirdness with this we should investigate.
