### ISSUE TITLE
Adding List, Char, and Text utilities post-dogfooding 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/base#40]
@hojberg, @pchiusano and I added a few functions to base. 

Also, apologies if I have massively messed up the PR process once again. 🤞 

## Controversial Decisions: 

* `Text.trim` walks the string twice. We can write a more efficient but less concise function if need be. 
* We weren't sure what `findMap` should be called. 
* `Char.isWhitespace` defines whitespace as `\s`  `\t` `\n` and `\r` - but maybe things like "form-feed" should also be considered whitespace? We weren't sure.  

## Code review

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/rlmark/my-unison-repo3:.basePr
    
  Added definitions:
  
     List.dropLastWhile.tests.all  : [Result] (+4 metadata)
     Text.trim.tests.all           : [Result] (+5 metadata)
     List.dropLastWhile.doc        : base.Doc (+3 metadata)
     Text.dropLastWhile.doc        : base.Doc (+3 metadata)
     Text.dropWhile.doc            : base.Doc (+3 metadata)
     List.findMap.doc              : base.Doc (+3 metadata)
     Either.isLeft.doc             : base.Doc (+3 metadata)
     Either.isRight.doc            : base.Doc (+3 metadata)
     Char.isWhitespace.doc         : base.Doc (+2 metadata)
     List.dropLastWhile            : (a ->{g} Boolean) -> [a] ->{g} [a] (+3 metadata)
     Text.dropLastWhile            : (Char ->{g} Boolean) -> Text ->{g} Text (+3 metadata)
     Text.dropWhile                : (Char ->{g} Boolean) -> Text ->{g} Text (+3 metadata)
     Text.trim.tests.edges         : [Result] (+5 metadata)
     List.findMap.tests.ex1        : [Result] (+4 metadata)
     List.findMap.tests.ex2        : [Result] (+3 metadata)
     List.findMap                  : (a ->{g} Optional b) -> [a] ->{g} Optional b (+3 metadata)
     Either.isLeft                 : Either a b -> Boolean (+3 metadata)
     Either.isRight                : Either a b -> Boolean (+3 metadata)
     Char.isWhitespace             : Char -> Boolean (+3 metadata)
     List.dropLastWhile.tests.last : [Result] (+4 metadata)
     List.dropLastWhile.tests.none : [Result] (+3 metadata)
     Text.trim.tests.none          : [Result] (+5 metadata)
     Text.trim                     : Text -> Text (+3 metadata)

**Comment by runarorama** [comment]
Great! 

I think we should at some point update `isWhitespace` to include vertical tabs and any Unicode space characters (see https://www.compart.com/en/unicode/category/Zs) like "em space", "en space", and nbsp.

**Comment by runarorama** [comment]
`dropLastWhile` is already in `base` as `List.dropRightWhile`

**Comment by runarorama** [comment]
> Great!
> 
> I think we should at some point update `isWhitespace` to include vertical tabs and any Unicode space characters (see https://www.compart.com/en/unicode/category/Zs) like "em space", "en space", and nbsp.

I've made this change.

**Comment by runarorama** [comment]
Merged in base hash `#q7s6r7mr8k`. 🌈🌟
