### ISSUE TITLE
Exception.bracket and finally don't necessarily run end/close

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#41]
It's pretty easy to create a call to `Exception.bracket` (and similarly `Exception.finally`) in which the end/close callback is never actually called. This makes it prone to resource leaks.

I don't _think_ that it's possible to implement a safe version of these functions with their current type signatures. They currently allow any `g` ability in the provided functions, but one of these abilities could result in early termination.

If you `run testBracket` with the following example, you'll never see `closing file handle` printed.

```haskell
testBracket : '{.base.IO, .base.Exception} ()
testBracket _ =
  open : () -> {.base.IO, .base.Exception, .base.Abort} Text
  open _ =
    .base.io.printLine "opening file handle"
    "pretend I'm a file handle"
  close : Text -> {.base.IO, .base.Exception, .base.Abort} ()
  close filehandle =
    .base.io.printLine "closing file handle"
  useFileHandle : Text -> {.base.IO, .base.Exception, .base.Abort} ()
  useFileHandle fileHandle =
      .base.io.printLine ("begin useFileHandle")
      abort
      .base.io.printLine ("end useFileHandle")
  go _ = Exception.bracket open close useFileHandle
  !(.base.Abort.toOptional go)
  ()
```

**Comment by ceedubs** [comment]
@rlmark it looks like this was introduced in #3. Do you have thoughts on how we handle this? It would be great if the current type signature could be supported, so I'm hoping that someone proves me wrong.

**Comment by pchiusano** [comment]
I think the answer is just: don't use these functions with `g` that allows for early termination. (I think also problematic will be any `g` that uses the continuation multiple times.) Type signatures can be used to constrain things at use sites, and I think for these we could add specialized versions: `finalize.io`, `bracket.io`, etc, where `g` is just `{IO}` and no other abilities (besides `Exception`) are allowed. They would literally just be aliases of the existing functions but with a different signature. WDYT?

In general, I like making functions as ability-polymorphic as possible, since you never know where effects will be useful, even if not all combinations of abilities are going to be sensible.

**Comment by ceedubs** [comment]
@pchiusano I think that change sounds reasonable, but we should probably add some docs warning about how you can get into trouble here. I'm also a bit inclined to use names that don't seem quite so safe (especially `finally`), but maybe I'm worrying too much.

**Comment by ceedubs** [comment]
I guess that I signed up to be the one to add the docs :)

**Comment by rlmark** [comment]
Ah, yeah @ceedubs I see your point. Bracket has some preliminary docs but they could definitely use this caveat! I'm also open to renaming 'finally' - as I agree that could trip folks up, though I'm not sure what that name should be 😅

**Comment by runarorama** [comment]
I attempt to address this with the `Resource` ability posted here:

https://share.unison-lang.org/@runarorama/code/latest/namespaces/public/resource/trunk/

This might make its way into Base at some point

**Comment by runarorama** [comment]
I've made some changes to the docs for `bracket` and `finally`, to call this issue out:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/130916/222812238-18457e45-87b9-457c-a74c-dadc902700df.png">

**Comment by ceedubs** [comment]
@runarorama thank you! Sorry that I never got around to doing something about this.
