### ISSUE TITLE
Draft: new Abort/Store/Optional functions

### ISSUE THREAD

**Issue by anovstrup** [unisonweb/base#42]
* This PR renames `Abort.toDefault!` -> `Abort.toDefaultValue!` and repurposes `Abort.toDefault!` to take a delayed computation as a default instead of a default value.  It also renames `Abort.toDefault` -> `Abort.toDefaultValue` and repurposes `Abort.toDefault` for the delayed version of `Abort.toDefault!`. An `Optional.getOrElse'` function, which takes a delayed default, is also added.
* The PR also renames the sort-of-useless definition of `Store.local` to `Store.local.deprecated` ("useless", because `Store.withInitialValue` could just be used instead) and introduces `Store.local!` for a function that allows one to operate on a partial state, given getter/setter functions for the whole state. ~~A similar `Store.focus!` function is also introduced that uses a `Lens` type to encapsulate the getter/setter. `Store.local` is repurposed for the delayed version of `Store.local!`, and `Store.focus` provides a delayed version of `Store.focus!`.~~

## Code review

The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/anovstrup/unison-all:.prs.base.abort

  Updates:

     Abort.toDefault : a -> '{g, Abort} a -> '{g} a
     ↓
     Abort.toDefault : '{g} a -> '{g, Abort} a -> '{g} a
     +  licenses.mit_2020 : License
     +  author            : Author

     Abort.toDefault! : a -> '{g, Abort} a ->{g} a
     ↓
     Abort.toDefault! : '{g} a -> '{g, Abort} a ->{g} a
     +  licenses.mit_2020 : License
     +  author            : Author

     Abort.toDefault!.doc : Doc
     ↓
     Abort.toDefault!.doc : Doc
     -  authors.jamessully  : Author
     -  licenses.jamessully : License
     +  licenses.mit_2020   : License
     +  author              : Author

     Abort.toDefault!.handler : a -> Request {Abort} a -> a
     ↓
     Abort.toDefault!.handler : '{g} a -> Request {Abort} a ->{g} a
     +  licenses.mit_2020 : License
     +  author            : Author

     Abort.toDefault.doc : Doc
     ↓
     Abort.toDefault.doc : Doc
     +  licenses.mit_2020   : License
     +  authors.jamessully  : Author
     +  author              : Author
     +  licenses.jamessully : License

     Store.local : a -> '{g, Store a} v ->{g, Store a} v
     ↓
     Store.local : (a ->{g} b) -> (a ->{g} b ->{g} a) -> '{g, Store b} v -> '{g, Store a} v
     -  deprecated.doc    : Doc.Deprecated
     +  licenses.mit_2020 : License
     +  author            : Author

     Store.local.doc : Doc.Deprecated
     ↓
     Store.local.doc : Doc
     +  licenses.mit_2020 : License
     +  author            : Author

  Added definitions:

     Optional.getOrElse'.doc   : Doc (+2 metadata)
     Store.local!.doc          : Doc (+2 metadata)
     Abort.toDefaultValue.doc  : Doc (+2 metadata)
     Abort.toDefaultValue!.doc : Doc (+4 metadata)
     Store.local!.examples.ex1 : (Text, Nat) (+2 metadata)
     Store.local!.tests.ex1    : [Result] (+3 metadata)
     Optional.getOrElse'       : '{e} a -> Optional a ->{e} a (+2 metadata)
     Store.local!              : (a ->{g} b)
                               -> (a ->{g} b ->{g} a)
                               -> '{g, Store b} v
                               ->{g, Store a} v (+2 metadata)

  Name changes:

    Original                     Changes
     Store.local.doc              Store.local.deprecated.doc (added)
                                  Store.local.doc (removed)

     Store.local.examples.ex1     Store.local.deprecated.examples.ex1 (added)
                                  Store.local.examples.ex1 (removed)

     Abort.toDefault!.handler     Abort.toDefaultValue!.handler (added)
                                  Abort.toDefault!.handler (removed)

     Store.local                  Store.local.deprecated (added)
                                  Store.local (removed)

     Store.local.test             Store.local.deprecated.test (added)
                                  Store.local.test (removed)

     Abort.toDefault              Abort.toDefaultValue (added)
                                  Abort.toDefault (removed)

     Abort.toDefault!             Abort.toDefaultValue! (added)
                                  Abort.toDefault! (removed)

**Comment by runarorama** [comment]
Is this still in the draft stage?

**Comment by anovstrup** [comment]
@runarorama In the sense that I wouldn't necessarily merge it without more tests / better docs, yes. But I would like feedback if you've got any before I go further.

**Comment by ceedubs** [comment]
Thanks for this PR, @anovstrup! I'm sorry for the lack of response. I've hesitated a bit because of the introduction of `Lens`. I've thought to myself that I'm not sure that anyone has really thought through what lenses should look like in Unison, and so do we really want to add a canonical `.base.Lens` at this point? Should `Lens` live in another lib outside of base? Having said that, your `Lens` looks quite reasonable, and I have no objections to it. It makes sense how it can be useful here.

@runarorama what are your thoughts?

**Comment by anovstrup** [comment]
@ceedubs I had the same reservations about including `Lens`.  I'd be happy to keep `Lens` and `Store.focus/Store.focus!` in a separate lib.

**Comment by ceedubs** [comment]
@anovstrup I was hoping that @runarorama might weigh in. But I do think that it maybe at least makes sense to move the lens stuff into another PR if not another lib. Thanks a lot!

**Comment by ChrisPenner** [comment]
I have a few thoughts on optics in unison; and I think something so foundational deserves PR all to themselves, so I'd prefer we leave them out of this one 😄 

Although the lens you present looks perfectly fine in isolation, I'm really curious how you would encode Traversals and Folds and how they would compose with one another without type classes or row polymorphism.

In theory you could use Van-Laarhoven optics, but It gets a bit tricky in unison because there's no equivalent to an Functor/Applicative/Monad hierarchy, we ONLY have Monadic power (i.e. Ability). It's likely we could figure something out if we stick to non-type-changing optics, but is that the direction we want to go?

Are optics even the right abstraction for a language like Unison and for Abilities?

If you've got an approach in mind though I'd love to see it in a separate PR!

**Comment by runarorama** [comment]
I'm going to close this for now, as the consensus seems to be that this should be at least 2 PRs to Base. I'm sympathetic to the idea that lenses should be in Base, but I'm also reluctant to add them in so casually.

I'm working on some guidelines for _what exactly should be in Base_, which I'll publish soon. The gist of it is that things should probably be in Base if at least one of these is true and none of them are false:

* Useful to a lot of developers ✅ 
* Likely to have a lot of dependents ✅ 
* Would be inconvenient to have competing implementations, or probably just has one "best" implementation ✅ 
* Not cutting-edge or unexplored design space ✅ 
* Highly stable. Frequent changes unlikely ✅ 
* Uncontroversial. Not an area of strong personal preference. ❓

**Comment by anovstrup** [comment]
I removed the `Lens` stuff from the PR and updated the description accordingly.

**Comment by runarorama** [comment]
Just wanted to let you know I'm on this, but won't have time to get it merged until the new year.

**Comment by runarorama** [comment]
This is merged in base hash `#n0bck9fc12`. Thanks! 🌈⭐️
