### ISSUE TITLE
Point to current base methods in Bag.convolve.tests.natural

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#45]
## Summary

The current `Bag.convolve.tests.natural` implementation refers to some terms that are no longer in base, and therefore just so hashes on Unison share. This also can prevent people from deleting old versions of base that they might have previously pulled.

### Before

```haskell
Bag.convolve.tests.natural =
  use gen boolean
  #rsk9km80mn
    100 ('let
      bx = !(#eikfnlp21q boolean)
      by = !(#eikfnlp21q boolean)
      f = !yesNo
      g = !yesNo
      o = !logic
      left = #plft6n9tqf (x y -> o (f x) (g y)) bx by
      right = #plft6n9tqf o (#dvrrafvt1b f bx) (#dvrrafvt1b g by)
      #pi4saqo9sp (#9cu0p9v21l left right))
```

### After

```haskell
  Bag.convolve.tests.natural : [Test.Result]
  Bag.convolve.tests.natural =
    use Bag ==
    use gen boolean
    test.runs
      100 ('let
        bx = !(bagOf boolean)
        by = !(bagOf boolean)
        f = !yesNo
        g = !yesNo
        o = !logic
        left = convolve (x y -> o (f x) (g y)) bx by
        right =
          use Bag map
          convolve o (map f bx) (map g by)
        test.expect (left == right))
```

## Code review

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load git@github.com:unisonweb/base:.trunk git@github.com:ceedubs/unison-dev:.pr.base.nomoreoldstuff
  
  Updates:
  
     Bag.convolve.tests.natural : [Test.Result]
     ↓
     Bag.convolve.tests.natural : [Test.Result]
     +  unisoncomputing2021 : License
     +  unisoncomputing2020 : License
     +  authors.ceedubs     : Author
     +  isTest              : IsTest
     +  runarorama          : Author
  
     patch patch (added 1 updates)

**Comment by runarorama** [comment]
Merged in `#q7s6r7mr8k`
