### ISSUE TITLE
Documentation Wanted 😄 

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/base#47]
If you're reading this, we'd love your help documenting our `base` library!

* Check out our Unison ["Getting Started" guide](https://www.unisonweb.org/docs);
* Next up, learn how to write docs in Unison! Docs in Unison are much more powerful than other languages, so check out our guide on [Documenting Unison Code](https://www.unisonweb.org/docs/documentation)
* Submit a Pull Request to our base library! [Here's a guide for that.](https://www.unisonweb.org/docs/codebase-organization)

**Comment by runarorama** [comment]
Pretty much everyting in Base has docs now, so I'm closing this for now.
