### ISSUE TITLE
BDD style test helpers and docs

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/base#48]
Adds helpful BDD-style test helpers to the testing library. By accepting both a label and a list of tests we avoid superfluous parens.

Also clears up confusion between `assert`s which are meant to be used in regular code vs the expectation helpers which are specifically for tests. I changed the new `expectEquals` to return a Test so that it can be used inline without an "expect"

Assertions for "real" code were moved to the Debug namespace.

Adds a readme to the test namespace which shows an example of how to write readable tests. Here's an example of what things look like when doing non-trivial tests (assume each block includes multiple tests even though I've only provided one):

## Before
```
test> readme.example =
    test.run <| tests [
      label "Text.reverse" <| (
        tests [
          label "reverses a word" let
           result = Text.reverse "pomegranate"
           expected = "etanargemop"
           expect (assertEquals expected result)
       ])
    ]
```

## After
```
test> readme.example =
  run <| describe "Text.reverse" [
    it "reverses a word" let
      result = Text.reverse "pomegranate"
      expected = "etanargemop"
      expectEquals expected result
    ,
]

```

## Code review
  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/ChrisPenner/unison-codebase:.prs.base._newtest

  Updates:

     patch test.patch (added 2 updates)

  Added definitions:

     test.describe         : Text -> [Test] -> Test (+2 metadata)
     test.describe.doc     : Doc (+2 metadata)
     test.expectEquals.doc : Doc (+2 metadata)
     test.it.doc           : Doc (+2 metadata)
     test.readme.example   : [Result] (+2 metadata)
     test.expectEquals     : a -> a -> Test (+2 metadata)
     test.it               : Text -> Test -> Test (+2 metadata)
     test.readme           : Doc (+2 metadata)

  Name changes:

    Original                  Changes
     test.assert               Debug.assert (added)
                               test.assert (removed)

     test.assertEquals         Debug.assertEquals (added)
                               test.assertEquals (removed)

     test.assert.doc           Debug.assert.doc (added)
                               test.assert.doc (removed)

     test.assertEquals.doc     Debug.assertEquals.doc (added)
                               test.assertEquals.doc (removed)

**Comment by ceedubs** [comment]
I definitely like the `expectEquals` addition.

Personally I've never been into the BDD DSLs that attempt to read like English sentences. It works fine in an example, but I think that it's confusing to newcomers to `ls` the methods in `.base.test` and find functions with names like `it`.

I could totally see a BDD-style library forming out of this sort of thing. But I fear that it might be a bit too opinionated for `.base.test`. I wonder if these combinators hold up as useful in non-BDD styles (with different names)?

**Comment by ChrisPenner** [comment]
I'd say it's just as opinionated to use "generic" names as it is to use BDD, they're just different opinions aren't they? 😋 
But for my side I don't care nearly as much about the *names* of the combinators as I do about the combinators themselves being nice to work with, promoting good practices (i.e. named tests) and reducing boilerplate & redundancy.

**Comment by runarorama** [comment]
I'm with @ceedubs on this one. I think this is great, but probably doesn't belong in Base.

**Comment by ChrisPenner** [comment]
No worries, moved to `.chrispenner.bddtest` on share.
