### ISSUE TITLE
Add library for representing durations

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/base#49]
Before submitting a pull request, please doublecheck that you have included

## Code review

.> pr.create https://github.com/unisonweb/base:.trunk https://github.com/ChrisPenner/unison-  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/ChrisPenner/unison-codebase:.prs.base._duration2

  Updates:

     metadata.licenses.unisoncomputing2021 : License
     +  duration.!= : Duration -> Duration -> Boolean

  Added definitions:

     unique type duration.Duration (+3 metadata)
     duration.Duration.Nanoseconds     : Nat -> Duration
     duration.!=                       : Duration -> Duration -> Boolean (+3 metadata)
     duration.%                        : Duration -> Duration -> Duration (+3 metadata)
     duration.*                        : Nat -> Duration -> Duration (+3 metadata)
     duration.+                        : Duration -> Duration -> Duration (+3 metadata)
     duration.-                        : Duration -> Duration -> Duration (+3 metadata)
     duration.<                        : Duration -> Duration -> Boolean (+3 metadata)
     duration.<=                       : Duration -> Duration -> Boolean (+3 metadata)
     duration.==                       : Duration -> Duration -> Boolean (+3 metadata)
     duration.>                        : Duration -> Duration -> Boolean (+3 metadata)
     duration.>=                       : Duration -> Duration -> Boolean (+3 metadata)
     duration.asHours                  : Duration -> Nat (+3 metadata)
     duration.asMicroseconds           : Duration -> Nat (+3 metadata)
     duration.asMilliseconds           : Duration -> Nat (+3 metadata)
     duration.asMinutes                : Duration -> Nat (+3 metadata)
     duration.asNanoseconds            : Duration -> Nat (+3 metadata)
     duration.asSeconds                : Duration -> Nat (+3 metadata)
     duration.displayDuration          : Duration -> Text (+3 metadata)
     duration.!=.doc                   : Doc (+2 metadata)
     duration.%.doc                    : Doc (+2 metadata)
     duration.+.doc                    : Doc (+2 metadata)
     duration.-.doc                    : Doc (+2 metadata)
     duration.<.doc                    : Doc (+2 metadata)
     duration.<=.doc                   : Doc (+2 metadata)
     duration.==.doc                   : Doc (+2 metadata)
     duration.>.doc                    : Doc (+2 metadata)
     duration.>=.doc                   : Doc (+2 metadata)
     duration.Duration.doc             : Doc
     duration.asHours.doc              : Doc
     duration.asMicroseconds.doc       : Doc
     duration.asMilliseconds.doc       : Doc
     duration.asMinutes.doc            : Doc
     duration.asNanoseconds.doc        : Doc
     duration.asSeconds.doc            : Doc
     duration.displayDuration.doc      : Doc (+1 metadata)
     duration.hour.doc                 : Doc (+2 metadata)
     duration.microsecond.doc          : Doc (+2 metadata)
     duration.millisecond.doc          : Doc (+2 metadata)
     duration.minute.doc               : Doc (+2 metadata)
     duration.nanosecond.doc           : Doc (+2 metadata)
     duration.second.doc               : Doc (+2 metadata)
     duration.hour                     : Duration (+3 metadata)
     duration.microsecond              : Duration (+3 metadata)
     duration.millisecond              : Duration (+3 metadata)
     duration.minute                   : Duration (+3 metadata)
     duration.nanosecond               : Duration (+3 metadata)
     duration.readme                   : Doc (+3 metadata)
     duration.Duration.tests.roundtrip : [Result] (+1 metadata)
     duration.second                   : Duration (+3 metadata)
     duration.displayDuration.tests    : [Result] (+1 metadata)

     patch duration.patch (added 21 updates)

  Name changes:

    Original                                  Changes
     metadata.authors.chrispenner

     metadata.copyrightHolders.chrispenner

     metadata.licenses.chrispenner             metadata.licenses.chrisPenner2021 (added)
                                               metadata.licenses.chrispenner (removed)

     metadata.authors.chrispenner.guid

**Comment by runarorama** [comment]
Merged in `v3` branch. Thanks! 🌈⭐
