### ISSUE TITLE
Switch List.initialize to be tail recursive and add new docs for it

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#5]
Also provided updated docs.

<img width="1195" alt="Screen Shot 2021-06-04 at 10 42 50 AM" src="https://user-images.githubusercontent.com/11074/120827997-a2272880-c521-11eb-8009-e313c67bca2b.png"> 

 The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/pchiusano/unisoncode:.prs.initialize

I'd use the squash merged version for this, my branch has a bit of local churn.

    Updates:
  
     List.initialize : Nat -> (Nat ->{e} a) ->{e} [a]
     ↓
     List.initialize : Nat -> (Nat ->{e} a) ->{e} [a]
     -  unisoncomputing2020            : License
     -  base.List.initialize.doc       : Doc.Deprecated
     +  unisoncomputing2021            : License
     +  pchiusano                      : Author
     +  authors.vanev                  : Author
     +  initialize.List.initialize.doc : Doc
     +  runarorama                     : Author
    
     List.initialize.doc : Doc.Deprecated
     ↓
     List.initialize.doc : Doc
     -  unisoncomputing2020 : License
     +  unisoncomputing2021 : License
     +  pchiusano           : Author
     +  authors.vanev       : Author
     +  runarorama          : Author
  
    There were 6 auto-propagated updates.
  
     patch patch (added 1 updates)

**Comment by rlmark** [comment]
Docs look great!

**Comment by runarorama** [comment]
Merged in base hash `#bkt9a2cpnf`
