### ISSUE TITLE
Rename `.` compose from base.

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/base#50]
Before submitting a pull request, please doublecheck that you have included

* [x] `Doc`s linked for types and terms as needed
* [x] `Author` and `License` metadata linked
* [x] `Test`s, where appropriate (only one valid implementation for this type, no tests required.

## Code review

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/ChrisPenner/unison-codebase:.prs.base._compose

  Added definitions:

     <<     : (b ->{𝕖} c) -> (a ->{𝕖} b) -> a ->{𝕖} c
     >>     : (a ->{𝕖} b) -> (b ->{𝕖} t) -> a ->{𝕖} t
     <<.doc : Doc
     >>.doc : Doc

  Name changes:

    Original    Changes
     .       ┐   . (removed)
     compose ┘

**Comment by pchiusano** [comment]
Cool, but let's do `<<` and `>>`. Less typing!

`>>` and `<<` were taken in Haskell at the time the arrow stuff was introduced. We're not constrained by that here.

**Comment by runarorama** [comment]
I get an error pulling this. 

```
Encountered Exception: DatabaseIntegrityError (NoObjectForPrimaryHashId (HashId 153)) in term metadata
CallStack (from HasCallStack):
  error, called at src/Unison/Codebase/SqliteCodebase.hs:293:88 in unison-parser-typechecker-0.0.0-3ZCXoyD1xK78Xx2xOdGxbl:Unison.Codebase.SqliteCodebase
  getCycleLen, called at src/Unison/Codebase/SqliteCodebase.hs:578:43 in unison-parser-typechecker-0.0.0-3ZCXoyD1xK78Xx2xOdGxbl:Unison.Codebase.SqliteCodebase
```

**Comment by ChrisPenner** [comment]
I'm not sure what's up there, others have reported the same. I may need to just re-write this at some point.

**Comment by aryairani** [comment]
I'd say figuring out the cause of the crash is more valuable than renaming `.` / `compose` in base, plus the former can enable the latter :)

**Comment by ChrisPenner** [comment]
That is, assuming that my codebase isn't just messed up from a development branch of ucm; but yeah probably worth looking into 😄

**Comment by pchiusano** [comment]
I'd try `debug.clear-cache` @ChrisPenner if you haven't already. It could just be a bad cache value (from a type that's hasn't been added to the codebase) getting sync'd.

**Comment by ChrisPenner** [comment]
@pchiusano Good thought!
Unfortunately doesn't seem to have sorted things out in this case:
* I ran it on my codebase, then re-pushed, then pulled that codebase from remote
* I ran the pull-request.load and it failed as before,
* Then I realized that since a push just runs a 'sync' rather than actually replacing the remote codebase I manually replaced the codebase in my cached git repo and pushed that myself to ensure it was really replaced,
* Unfortunately, this didn't work either, same error.

The error suggests the missing hash is for some term metadata, so now I'm curious if somewhere in our syncing code we're failing to sync metadata if it's missing a name, or maybe if it lives in a different namespace.

I'll dig deep into our syncing code and try to reproduce when I have time 👍🏼

**Comment by aryairani** [comment]
It's probably a good clue that `pull` works but `pull-request.load` doesn't.

**Comment by ChrisPenner** [comment]
Good point Arya, I did some experimenting, it can pull both branches separately, it's actually when you try to `merge` them that the hiccup happens, I think there's some bad metadata somewhere in one of the histories.

Still not sure how it actually ended up in that state though 😓

**Comment by aryairani** [comment]
@ChrisPenner It would have to be something wrong with the causal or the branch serialization or syncing if those are referring to something that isn’t forced to exist.

Once you find exactly how the missing thing is being referenced, look at the code that should have ensured that thing wasn’t missing, and that should be our culprit.

**Comment by aryairani** [comment]
> Good point Arya, I did some experimenting, it can pull both branches separately, it's actually when you try to `merge` them that the hiccup happens, I think there's some bad metadata somewhere in one of the histories.
> 
> Still not sure how it actually ended up in that state though 😓

Hmm, I was just looking at this again. If we can pull both branches separately, wouldn't that mean that neither branch's history has bad metadata? And that merging the two histories also shouldn't?

**Comment by ChrisPenner** [comment]
It looks like `.` has been removed from base, closing this 👍🏼
