### ISSUE TITLE
Add List.dropLast doc

### ISSUE THREAD

**Issue by KF525** [unisonweb/base#51]
## Code review

.> pull-request.create https://github.com/unisonweb/base:.trunk.List https://github.com/KF525/unison-code-v1:.prs.List                                                       
                                                              
  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base:.trunk.List https://github.com/KF525/unison-code-v1:.prs.List
  
  Added definitions:
  
     dropLast.doc : Doc (+2 metadata)

**Comment by ceedubs** [comment]
@KF525 thanks a lot! This is now merged into the `base.trunk` namespace at hash `#je67q0406o`.

Apologies for the delay on a really straightforward PR.
