### ISSUE TITLE
Fix a few non-roundtripping terms and types

### ISSUE THREAD

**Issue by runarorama** [unisonweb/base#53]
This replaces `void` and friends, as well as adding placeholder names for `IO.Deprecated` constructors, so that these definitions can roundtrip through the pretty-printer/parser. The goal is ultimately that there will be nothing in `base` that doesn't roundtrip.

I also added documentation for `Boolean` while I was in there. I added a few Boolean ops as part of getting ready to replace the function `logic` with a version that can roundtrip, and decided to update the docs while I was at it.

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk git@github.com:runarorama/bv2:.roundtrip1

  Updates:

     absurd : Void -> a
     ↓
     absurd : Void -> a
     -  base.absurd.doc     : Doc.Deprecated
     +  unisoncomputing2021 : License
     +  atacratic.mit_2020  : License
     +  absurd.doc          : Doc
     +  authors.atacratic   : Author
     +  runarorama          : Author

     absurd.doc : Doc.Deprecated
     ↓
     absurd.doc : Doc
     +  unisoncomputing2021 : License
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     absurdly : '{e} Void ->{e} a
     ↓
     absurdly : '{e} Void ->{e} a
     +  unisoncomputing2021 : License
     +  atacratic.mit_2020  : License
     +  authors.atacratic   : Author
     +  runarorama          : Author

     Boolean.and : Boolean -> Boolean -> Boolean
     -  base.Boolean.and.doc : Doc.Deprecated
     +  Boolean.and.doc      : Doc

     Boolean.and.doc : Doc.Deprecated
     ↓
     Boolean.and.doc : Doc
     +  unisoncomputing2021 : License
     +  unisoncomputing2020 : License
     +  runarorama          : Author

     Boolean.given : Boolean -> Boolean -> Boolean
     -  base.Boolean.given.doc : Doc.Deprecated
     +  Boolean.given.doc      : Doc

     Boolean.given.doc : Doc.Deprecated
     ↓
     Boolean.given.doc : Doc
     +  unisoncomputing2021 : License
     +  atacratic.mit_2020  : License
     +  authors.atacratic   : Author
     +  runarorama          : Author

     Boolean.implies : Boolean -> Boolean -> Boolean
     -  base.Boolean.implies.doc : Doc.Deprecated
     +  Boolean.implies.doc      : Doc

     Boolean.implies.doc : Doc.Deprecated
     ↓
     Boolean.implies.doc : Doc
     +  unisoncomputing2021 : License
     +  atacratic.mit_2020  : License
     +  authors.atacratic   : Author
     +  runarorama          : Author

     Boolean.or : Boolean -> Boolean -> Boolean
     -  base.Boolean.or.doc : Doc.Deprecated
    
     ...
                                              ->{IO.Deprecated} Either
                                                Error.Deprecated (Optional BufferMode.Deprecated)
     IO.Deprecated.Op28                       : Handle.Deprecated
                                              ->{IO.Deprecated} Either Error.Deprecated Int
     IO.Deprecated.Op29                       : FilePath
                                              ->{IO.Deprecated} Either Error.Deprecated ()
     io.deprecated.ErrorType.Deprecated.Op3   : ErrorType.Deprecated
     IO.Deprecated.Op3                        : '{IO.Deprecated} a
                                              -> (a ->{IO.Deprecated} b)
                                              -> (a ->{IO.Deprecated} c)
                                              ->{IO.Deprecated} Either Error.Deprecated c
     IO.Deprecated.Op30                       : FilePath
                                              ->{IO.Deprecated} Either Error.Deprecated ()
     IO.Deprecated.Op31                       : FilePath
                                              ->{IO.Deprecated} Either Error.Deprecated ()
     IO.Deprecated.Op32                       : FilePath
                                              ->{IO.Deprecated} Either Error.Deprecated ()
     IO.Deprecated.Op33                       : {IO.Deprecated} (Either Error.Deprecated EpochTime)
     IO.Deprecated.Op34                       : Handle.Deprecated
                                              ->{IO.Deprecated} Either Error.Deprecated Boolean
     IO.Deprecated.Op35                       : Handle.Deprecated
                                              ->{IO.Deprecated} Either Error.Deprecated Boolean
     IO.Deprecated.Op36                       : Handle.Deprecated
                                              ->{IO.Deprecated} Either Error.Deprecated Boolean
     IO.Deprecated.Op37                       : Handle.Deprecated
                                              -> Text
                                              ->{IO.Deprecated} Either Error.Deprecated ()
     io.deprecated.ErrorType.Deprecated.Op4   : ErrorType.Deprecated
     IO.Deprecated.Op4                        : Handle.Deprecated
                                              ->{IO.Deprecated} Either Error.Deprecated Text
     io.deprecated.ErrorType.Deprecated.Op5   : ErrorType.Deprecated
     IO.Deprecated.Op5                        : Handle.Deprecated
                                              ->{IO.Deprecated} Either Error.Deprecated Text
     io.deprecated.ErrorType.Deprecated.Op6   : ErrorType.Deprecated
     IO.Deprecated.Op6                        : FilePath
                                              ->{IO.Deprecated} Either Error.Deprecated EpochTime
     io.deprecated.ErrorType.Deprecated.Op7   : ErrorType.Deprecated
     IO.Deprecated.Op7                        : Handle.Deprecated
                                              ->{IO.Deprecated} Either Error.Deprecated ()
     IO.Deprecated.Op8                        : {IO.Deprecated} (Either Error.Deprecated FilePath)
     IO.Deprecated.Op9                        : {IO.Deprecated} (Either Error.Deprecated FilePath)
     io.deprecated.Socket.Deprecated.Socket   : Text -> Socket.Deprecated
     io.deprecated.Socket.Deprecated.ThreadId : Text -> ThreadId.Deprecated
     Boolean.docs.binaryTruthTable            : ∀ g1 g.
                                                Text
                                                -> (Boolean ->{g} Boolean ->{g1} Boolean)
                                                ->{g1, g} Doc (+2 metadata)
     Boolean.butNot                           : Boolean -> Boolean -> Boolean (+2 metadata)
     Boolean.doc                              : Doc (+2 metadata)
     Boolean.butNot.doc                       : Doc (+2 metadata)
     Boolean.iff.doc                          : Doc (+2 metadata)
     Boolean.inhibitedBy.doc                  : Doc (+2 metadata)
     Boolean.nand.doc                         : Doc (+2 metadata)
     Boolean.nor.doc                          : Doc (+2 metadata)
     Boolean.not.doc                          : Doc (+2 metadata)
     Boolean.inhibitedBy                      : Boolean -> Boolean -> Boolean (+2 metadata)
     Boolean.nand                             : Boolean -> Boolean -> Boolean (+2 metadata)
     Boolean.nor                              : Boolean -> Boolean -> Boolean (+2 metadata)
     Boolean.docs.unaryTruthTable             : Text
                                              -> (Boolean ->{g} Boolean)
                                              -> Doc (+2 metadata)

  Name changes:

    Original       Changes
     Boolean.==     Boolean.iff (added)

**Comment by aryairani** [comment]
We reviewed this today. `Boolean.docs.binaryTruthTable` is super cool!

When we reached `Boolean.inhibitedBy` we started to wonder if all of these functions actually deserve names in `base`, or if they are just adding to the complexity of the library without benefit? https://wiki.haskell.org/Fairbairn_threshold. 

Otherwise, seems fine! We held off merging.
