### ISSUE TITLE
systemTimeMicroseconds should be an alias

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#54]
`base.io.systemTimeMicroseconds` should be a proper `alias.term` for the corresponding builtin.

Right now it is a function that delegates through to the builtin:

```
  .base.io.systemTimeMicroseconds : '{IO} Int                                                                                           
  .base.io.systemTimeMicroseconds = IO.systemTimeMicroseconds 
```

This means that it has a different hash than the builtin, and it's possible to get into a situation where you can't delete a `.builtin` namespace, because you don't have a corresponding term for the builtin hash provided by `.base`.

I was planning on submitting a "PR" but I realized that I don't know how to do this in a way that will be update-friendly for users. If I delete the existing term and then replace it with an alias, that won't automatically update for users of base, will it?

See [this Slack discussion](https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1635178447018500).

**Comment by ceedubs** [comment]
While this is being worked on, it's probably worth checking whether there is a similar issue for other builtins.

**Comment by pchiusano** [comment]
We could add a replacement to the default patch I guess. Kind of annoying to force an upgrade on people for this when the version in base is fine but just has a pointless level of indirection.

WDYT of the following:

Rename the one with the extra indirection to `io.sleepMicroseconds.deprecated` and create a patch `io.sleepMicroseconds.patch` which has just this replacement. Add a `Doc` on the deprecated one about how to upgrade. Thus no one is forced to upgrade, and when viewing code you'll see that `.deprecated` in the name, providing a good clue that your code is out of date along with a link to the doc which explains how to upgrade.

I feel like this is sort of a common situation, where some code is being updated but the old version is okay - you want to encourage people to upgrade For Reasons but not force it.

**Comment by ceedubs** [comment]
@pchiusano I don't think that moving the term to `io.sleepMicroseconds.deprecated` will fix the problem that I'm having where someone has a `.builtins` namespace that is causing ambiguity between `builtin.Universal.>=` and `Nat.>=` and can't delete said namespace because `base` is referencing terms in it.

**Comment by pchiusano** [comment]
Right. You could rename `builtin.Universal.>=` locally to `builtin.Universal.gteq` right?

**Comment by ceedubs** [comment]
@pchiusano I could. My concern was that anyone else who tries to use `>=` on `Nat` (which seems like a pretty common use-case) would run into the same issue. I don't really care about the indirection in `systemTimeMicroseconds` at all other than that it indirectly makes it a pain for people to compare `Nat`s.

**Comment by pchiusano** [comment]
@ceedubs right, but `Universal.>=` doesn't exist in base (anymore). Maybe we should remove it from the default `builtin` namespace, but the idea is that nobody should be using that - people should get their builtins from base.

**Comment by ceedubs** [comment]
@pchiusano okay it sounds like maybe I did something that I shouldn't have and so I have a `builtin` namespace but other people don't.

In that case, I'll keep this issue open, and the `.deprecated` solution seems reasonable, but it also doesn't seem like a very big deal if there is a slight amount of indirection in the the `systemTimeMicroseconds` function.

**Comment by runarorama** [comment]
Closing this for now
