### ISSUE TITLE
Change Stream.iterate return type from () to Void

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#55]
This changes the return type of `Stream.iterate` and `Stream.iterate!` to be `Void` instead of `()` (without actually changing the implementation at all) to make it clear from the type that these generate a non-terminating result.

## Code review

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load git@github.com:unisonweb/base:.trunk git@github.com:ceedubs/unison-dev:.pr.base.iteratevoid
  
  Updates:
  
     Stream.iterate : (a ->{g} a) -> a -> '{g, Stream a} ()
     ↓
     Stream.iterate : (a ->{g} a) -> a -> '{g, Stream a} Void
     +  unisoncomputing2021 : License
     +  authors.jamessully  : Author
     +  licenses.jamessully : License
     +  authors.ceedubs     : Author
    
     Stream.iterate! : (a ->{g} a) -> a ->{g, Stream a} ()
     ↓
     Stream.iterate! : (a ->{g} a) -> a ->{g, Stream a} Void
     +  unisoncomputing2021 : License
     +  authors.jamessully  : Author
     +  licenses.jamessully : License
     +  authors.ceedubs     : Author
  
    There were 3 auto-propagated updates.
  
     patch patch (added 2 updates)

**Comment by runarorama** [comment]
Merged in `v3` branch 🌈⭐
