### ISSUE TITLE
Add Throw.catchWith and Throw.toException

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#56]
Occasionally it's useful to handle thrown values and to convert between APIs that `throw` and those that `raise`.

## Code review

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load git@github.com:unisonweb/base:.trunk git@github.com:ceedubs/unison-dev:.pr.base.catchWith
  
  Added definitions:
  
     Throw.catchWith       : (e ->{g1} a) -> '{g2, Throw e} a ->{g1, g2} a (+2 metadata)
     Throw.catchWith.doc   : Doc (+2 metadata)
     Throw.toException.doc : Doc (+2 metadata)
     Throw.toException     : (e ->{g1} Failure)
                           -> '{g2, Throw e} a
                           ->{g1, g2, Exception} a (+2 metadata)

**Comment by runarorama** [comment]
Merged in `v3` branch 🌈⭐
