### ISSUE TITLE
`Nat.toBytesLittleEndian` uses big-endian encoding

### ISSUE THREAD

**Issue by hagl** [unisonweb/base#58]
Contrary to its name the function [Nat.toBytesLittleEndian](https://share.unison-lang.org/@7k32lmrc5i2412q3ujel1e9u5p50vp369htvhnec3csek296fe5vl2mif949cg4q2grir06ii1eighp9tbbghjka1kfughkjcnfcktg/namespaces/unison/base/;/terms/Nat/toBytesLittleEndian) encodes a Nat in big-endian format:
```
    1 | > Nat.toBytesLittleEndian 1
          ⧩
          0xs0000000000000001
  
    2 | > Nat.toBytesLittleEndian 1 === Bytes.encodeNat64le 1
          ⧩
          false
  
    3 | > Nat.toBytesLittleEndian 1 === Bytes.encodeNat64be 1
          ⧩
          true
```
Since there are built-in functions `Bytes.encodeNat64le` and `Bytes.encodeNat64be`, the `Nat.toBytesLittleEndian` could  use the corresponding one instead of shifting bits manually.

**Comment by ceedubs** [comment]
@hagl thank you for reporting this! You are right, this should use the builtins.

**Comment by runarorama** [comment]
Fixed in `v3` branch. Thanks!
