### ISSUE TITLE
Stream.take and take! request one more item than necessary

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#60]
If you call `Stream.take 3`, then only `3` values will be _emitted_ by the resulting stream, but 4 elements will actually be _requested_ of the input stream.

Consider the following function. Since we take `3` elements, I would expect that after the third element is emitted (`3`) there is not an additional call to `go`, and therefore the log message is never printed when `n` is `4`.

```haskell
main : '{IO, Exception} ()
main _ =
  go : Nat -> {Exception, IO, Stream Text} Void
  go n =
    msg = "n is " ++ (toText n)
    printLine msg
    Stream.emit msg
    go (increment n)
  
  partialStream = .base.Stream.take 3 '(go 1)
  results = Stream.toList! partialStream
  result = List.foldLeft (Text.++) "logs: " (intersperse ", " results)
  printLine result
```

However, this produces the following output:

```
n is 1
n is 2
n is 3
n is 4
logs: n is 1, n is 2, n is 3
```

This is because of an extra side-effecting `ask` in `Stream.take!`:

```haskell
  .base.Stream.take! : Nat -> '{g, Stream a} r ->{g, Stream a} Optional r
  .base.Stream.take! n s =
    use Ask ask
    pipe!
      '(Some !s) ('let
        base.repeat n '(Stream.emit ask)
        ask
        None)
```

However, if you remove that extra `ask`, it makes a subtle difference. _With_ the extra `ask`, if you request `3` elements and the stream has exactly `3` elements, then you will get back a `Some`. _Without_ the extra `ask` if you request `3` elements and a stream has exactly `3` elements, you will get back a `None`. This is ultimately because of how `pipe!.handler` is implemented. If there is an `ask` and there are no more elements of the input stream, it returns the value _returned_ (note this is different than emitted) by the input stream. This return value would otherwise be ignored in favor of the return value of the `Request` being handled.

```haskell
  .base.Stream.pipe!.handler i = cases
    { r }                -> r
    {Ask.ask -> resumeC} ->
      h : base.Request {Stream a} r ->{Stream b} r
      h = cases
        { r }                 -> r
        {Stream.emit a -> i'} -> handle resumeC a with .base.Stream.pipe!.handler i'
      handle !i with h
    {Stream.emit b -> k} ->
      Stream.emit b
      handle !k with .base.Stream.pipe!.handler i
```

**Comment by runarorama** [comment]
Do you have a suggestion for a fix?

*whispers* (better yet, could you fix it?)

**Comment by ceedubs** [comment]
@runarorama my inclination would be to remove the extra ask in take!. I think that this could surprise people in a bad way since doing take 3 on a 3 element stream would return None. However, I would think that usually when you take part of a stream you aren't really expecting the result at the end of the stream. If you want it you can write a more sophisticated handler.

However, I'd want to look at how take! I'm is currently used (if at all) in base, and it will be at least a week since I can get to this. Happy to work on it once I'm available though.

**Comment by runarorama** [comment]
Fixed with a new implementation of `take!`:

```
  data.Stream.take! : Nat -> '{g, Stream a} r ->{g, Stream a} Optional r
  data.Stream.take! n s =
    h n = cases
      {emit a -> k} ->
        use Nat >
        if n > 0 then
          emit a
          handle !k
          with
            use Nat -
            h (n - 1)
        else None
      { r }         -> Some r
    handle !s with h n
```
