### ISSUE TITLE
More flexible type signature for Stream.+:

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#61]
The `Stream.+:` type signature was `a -> '{Stream a} r -> '{Stream a} r`. However its implementation supports the more general (and significantly more useful) type signature `a -> '{g, Stream a} r -> '{g, Stream a} r`.

## Code review

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load git@github.com:unisonweb/base:.trunk git@github.com:ceedubs/unison-dev:.pr.base.streamprepend
  
  Updates:
  
     Stream.+: : a -> '{Stream a} r -> '{Stream a} r
     ↓
     Stream.+: : a -> '{g, Stream a} r -> '{g, Stream a} r
     +  unisoncomputing2021 : License
     +  anovstrup.mit_2020  : License
     +  authors.anovstrup   : Author
     +  authors.ceedubs     : Author
  
     patch patch (added 1 updates)

**Comment by pchiusano** [comment]
Test comment to check Slack notifications.

**Comment by runarorama** [comment]
Pushed to `v3` branch. 🌈⭐
