### ISSUE TITLE
helpers for `base.Text` are under `base.Text` but helpers for `base.Test` are under `base.test`

### ISSUE THREAD

**Issue by aryairani** [unisonweb/base#63]
(Upper vs lower case.)

Which should it be?

**Comment by runarorama** [comment]
The convention (so far) is that operations on a data type like `Test` should go under a namespace named after the type. The stuff in `test` is not all operations on `Test` (although admittedly some are).

**Comment by runarorama** [comment]
I moved a number of `Test` combinators into `test.Test` (the namespace for the `Test` type).
