### ISSUE TITLE
fix List.rangeClosed with lower-bound of 0

### ISSUE THREAD

**Issue by iamevn** [unisonweb/base#64]
Currently, List.rangeClosed doesn't work when the lower-bound is 0:
```
    1 | > List.rangeClosed 1 3
          ⧩
          [1, 2, 3]

    2 | > List.rangeClosed 0 3
          ⧩
          [0, 1, 2]

    3 | > List.rangeClosed 0 0
          ⧩
          []

    4 | > List.rangeClosed 1 1
          ⧩
          [1]
```

This PR fixes that and adds some tests:
```
    1 | > List.rangeClosed 1 3
          ⧩
          [1, 2, 3]

    2 | > List.rangeClosed 0 3
          ⧩
          [0, 1, 2, 3]

    3 | > List.rangeClosed 0 0
          ⧩
          [0]

    4 | > List.rangeClosed 1 1
          ⧩
          [1]

.prs.base._rangeClosed> cd List.rangeClosed
.prs.base._rangeClosed.List.rangeClosed> test

  Cached test results (`help testcache` to learn more)

  ◉ tests.empty        : Proved.
  ◉ tests.empty2       : Proved.
  ◉ tests.empty3       : Proved.
  ◉ tests.fromBig      : Proved.
  ◉ tests.fromOne      : Proved.
  ◉ tests.fromZero     : Proved.
  ◉ tests.rangeSize    : Passed 100 tests.
  ◉ tests.single0      : Proved.
  ◉ tests.single1      : Proved.
  ◉ tests.single99     : Proved.

  ✅ 10 test(s) passing

  Tip: Use view tests.empty to view the source of a test.

```

In the pull-request.create output, it shows that Licenses and Authors were added for `List.rangeClosed`, `Nat.rangeClosed`, and `README`. The first two merely had their definitions updated without touching metadata (they're aliases of each-other) and `README` is entirely untouched.

For the tests I added, I set myself as the author and used `metadata.licenses.unisoncomputing2021` as the license, should I instead add a BSD license specific to me in `metadata.licenses`?

## Code review

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/iamevn/unison-code:.prs.base._rangeClosed

  Updates:

     List.rangeClosed : Nat -> Nat -> [Nat]
     ↓
     List.rangeClosed : Nat -> Nat -> [Nat]
     +  unisoncomputing2021 : License
     +  runarorama          : Author

     Nat.rangeClosed : Nat -> Nat -> [Nat]
     ↓
     Nat.rangeClosed : Nat -> Nat -> [Nat]
     +  unisoncomputing2021 : License
     +  runarorama          : Author

     README : Doc
     ↓
     README : Doc
     +  unisoncomputing2021 : License
     +  simonhøjberg        : Author

    There were 4 auto-propagated updates.

     patch patch (added 1 updates)

  Added definitions:

     List.rangeClosed.tests._checkRangeClosed : Nat -> Nat -> [Nat] -> [Result] (+2 metadata)
     List.rangeClosed.tests.empty             : [Result] (+3 metadata)
     List.rangeClosed.tests.empty2            : [Result] (+3 metadata)
     List.rangeClosed.tests.empty3            : [Result] (+3 metadata)
     List.rangeClosed.tests.fromBig           : [Result] (+3 metadata)
     List.rangeClosed.tests.fromOne           : [Result] (+3 metadata)
     List.rangeClosed.tests.fromZero          : [Result] (+3 metadata)
     List.rangeClosed.tests.rangeSize         : [Result] (+3 metadata)
     List.rangeClosed.tests.single0           : [Result] (+3 metadata)
     List.rangeClosed.tests.single1           : [Result] (+3 metadata)
     List.rangeClosed.tests.single99          : [Result] (+3 metadata)

**Comment by runarorama** [comment]
Small thing: this PR is based off the M2k release but should have been based off trunk. So a change to `README` snuck in there.

On the copyright: you can submit another PR with an updated license if you would like. You can also just comment here and say that you're OK with assigning the copyright of these tests to Unison Computing.

**Comment by runarorama** [comment]
I fixed up the issue with the README and patch, and merged into trunk in hash `#dugkquov83`.

Thanks! 🌈⭐

**Comment by iamevn** [comment]
Thanks! Confirming that I'm okay with assigning the copyright to Unison Computing.
