### ISSUE TITLE
Add: `Boolean.toText`, `Char.!=`, `List.count`, `List.countEq`, `List.filterPresent`, `List.product`, `List.sum`, `Nat.subtractClamped`, `Set.intersects`

### ISSUE THREAD

**Issue by iamevn** [unisonweb/base#65]
Some additions I've found I wanted recently. I can split this out if that's preferred for review.

~~I'm not sure if `Nat.subtractClamped` is the best name for that function, I wanted it to be clear that it's not just subtraction since it saturates to 0.~~ 
Edit: removed `Nat.subtractClamped`, swapped added doc and tests to use `Nat.drop`

#### Similar notes as in #64:
In the pull-request.create output, it shows that Licenses and Authors were added for `README` but that's entirely untouched.

For the tests I added, I set myself as the author and used `metadata.licenses.unisoncomputing2021` as the license, should I instead add a BSD license specific to me in `metadata.licenses`?

## Code review

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/iamevn/unison-code:.prs.base._extras

  Updates:

     README : Doc
     ↓
     README : Doc
     +  unisoncomputing2021 : License
     +  simonhøjberg        : Author

     patch patch (added 1 updates)

  Added definitions:

     Boolean.toText                       : Boolean -> Text (+2 metadata)
     Boolean.toText.doc                   : Doc (+2 metadata)
     Char.!=                              : Char -> Char -> Boolean (+2 metadata)
     List.count                           : (a ->{g} Boolean) -> [a] ->{g} Nat (+2 metadata)
     List.count.doc                       : Doc (+2 metadata)
     List.countEq                         : a -> [a] -> Nat (+2 metadata)
     List.countEq.doc                     : Doc (+2 metadata)
     List.filterPresent                   : [Optional a] -> [a] (+2 metadata)
     List.filterPresent.doc               : Doc (+2 metadata)
     List.product                         : [Nat] -> Nat (+2 metadata)
     List.product.doc                     : Doc (+2 metadata)
     List.sum                             : [Nat] -> Nat (+2 metadata)
     List.sum.doc                         : Doc (+2 metadata)
     Nat.drop.doc                         : Doc (+2 metadata)
     Nat.drop.tests.many                  : [Result] (+3 metadata)
     Nat.drop.tests.positives             : [Result] (+3 metadata)
     Nat.drop.tests.zeroIfWouldBeNegative : [Result] (+3 metadata)
     Set.intersects                       : [Set a] -> Set a (+2 metadata)
     Set.intersects.doc                   : Doc (+2 metadata)
     Set.intersects.test                  : [Result] (+3 metadata)

**Comment by runarorama** [comment]
The issue with the README here is the same as with #64. You made your changes on top of M2k and then made the PR against trunk which has a different README.

I can fix that pretty easily.

**Comment by runarorama** [comment]
Made some changes to this.

* Avoid building an intermediate list in `count`.
* Removed `filterPresent`, as this exists as `somes`.
* Renamed `countEq` to `countElement`.
* Moved `sum` and `product` to the `Nat` namespace.
* Simplified tests on `drop`. This operation is completely specified by the following law:
    -  for all `x` and `y`, `drop x y + y` is  at least `x`, and `drop (x + y) y` is at most `x`.
    - That is, `drop` is _left adjoint_ to `+`.
* Removed reduntant case from `intersects`.
* Removed changes to README.

**Comment by runarorama** [comment]
Merged in base hash `#156u04ms93`. Thanks @iamevn! 🌈⭐

**Comment by runarorama** [comment]
@iamevn Can you make the same statement here that you're good with assigning the copyright to Unison Computing? Alternatively open a PR with your license.

**Comment by iamevn** [comment]
I'm okay with assigning the copyright to Unison Computing.
