### ISSUE TITLE
Rename `Nat.drop` to `Nat.-` and rename existing `Nat.-` to `Nat.subtractToInt`

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#70]
Right now we've got -

```haskell
(Nat.-) : Nat -> Nat -> Int
```

Originally the thinking was that subtracting nats can yield a negative number, hence `Int`. In practice, if you're working with things that are possibly negative, you're using `Int` in the first place, and even if you need to convert between the two types, you would use `Nat.toInt` and not rely on a subtraction operation to do the conversion.

For domains where negative numbers make no sense, I've noticed that subtraction clamped at 0 is usually what you want on `Nat` and I have literally never wanted the other behavior. For instance, a `Nat` is often used to track "how much work has been done", counting down to 0 from whatever number (say in the implementation of `take` or `drop` for some data structure). Clamping at 0 works perfectly for this and many other use cases.

Again if you really want something else, you can just do `Nat.toInt` on the arguments and then use `Int.-`.

I'd say the current `Nat.-` could be given some verbose name, like `Nat.subtractToInt`. I have literally never needed that function though.

@runarorama if this sounds good I can submit a PR along with docs.

Also random observation is it's still kind of surprising to me how often `Nat` is used and how little `Int` is used.

**Comment by runarorama** [comment]
Fixed in v3 branch
