### ISSUE TITLE
Update type signatures of several higher-order functions

### ISSUE THREAD

**Issue by runarorama** [unisonweb/base#72]
This updates the signatures of `(.)`, `andThen`, `List.foldLeft`, `List.foldRight`, and several other higher-order functions. Doing so fixes an issue where existing definitions involving these functions don't typecheck.

It also updates a few uses of `(.)` _that should not have typechecked in the first place_. Or at least, it's not clear why they would have typechecked.

 The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/runarorama/ubase2:.expandAbilitySigs

  Updates:

     . : (b ->{𝕖} c) -> (a ->{𝕖} b) -> a ->{𝕖} c
     ↓
     . : (b ->{e} c) -> (a ->{f} b) -> a ->{e, f} c
     +  authors.stew        : Author
     +  unisoncomputing2020 : License

     andThen : (a ->{𝕖} b) -> (b ->{𝕖} c) -> a ->{𝕖} c
     ↓
     andThen : (a ->{g} b) -> (b ->{h} c) -> a ->{g, h} c
     +  unisoncomputing2022 : License
     +  runarorama          : Author

     Bag.intersect : Bag a -> Bag a -> Bag a
     -  origin.Bag.intersect.doc : Doc.Deprecated
     +  base.Bag.intersect.doc   : Doc.Deprecated

     Boolean.given : Boolean -> Boolean -> Boolean
     ↓
     Boolean.given : Boolean -> Boolean -> Boolean
     -  origin.Boolean.given.doc : Doc.Deprecated
     +  unisoncomputing2022      : License
     +  authors.atacratic        : Author
     +  base.Boolean.given.doc   : Doc.Deprecated
     +  runarorama               : Author
     +  atacratic.mit_2020       : License

     compose : (b ->{𝕖} c) -> (a ->{𝕖} b) -> a ->{𝕖} c
     ↓
     compose : (b ->{e} c) -> (a ->{f} b) -> a ->{e, f} c
     +  authors.stew        : Author
     +  unisoncomputing2020 : License

     Function.uncurry : (a ->{e} b ->{e} c) -> (a, b) ->{e} c
     ↓
     Function.uncurry : (a ->{e} b ->{f} c) -> (a, b) ->{e, f} c
     +  unisoncomputing2022 : License
     +  runarorama          : Author
     +  uncurry.doc         : Doc.Deprecated
     +  unisoncomputing2020 : License

     Heap.fromList : [(k, v)] -> Optional (Heap k v)
     ↓
     Heap.fromList : [(k, v)] -> Optional (Heap k v)
     +  unisoncomputing2022 : License
     +  runarorama          : Author

     List.foldb : (a ->{𝕖} b) -> (b ->{𝕖} b ->{𝕖} b) -> b -> [a] ->{𝕖} b
     ↓
     List.foldb : (a ->{e} b) -> (b ->{f} b ->{g} b) -> b -> [a] ->{e, f, g} b
     +  unisoncomputing2022 : License
     +  runarorama          : Author

     List.foldLeft : (b ->{𝕖} a ->{𝕖} b) -> b -> [a] ->{𝕖} b
     ↓
     List.foldLeft : (b ->{e} a ->{f} b) -> b -> [a] ->{e, f} b
     +  unisoncomputing2022 : License
     +  runarorama          : Author
     +  List.foldLeft.doc   : Doc.Deprecated

     List.foldRight : (a ->{e} b ->{e} b) -> b -> [a] ->{e} b
     ↓
     List.foldRight : (a ->{e} b ->{f} b) -> b -> [a] ->{e, f} b
     +  unisoncomputing2022 : License
     +  List.foldRight.doc  : Doc.Deprecated
     +  runarorama          : Author
     +  unisoncomputing2020 : License

     List.groupSublistsBy : (a ->{e} a ->{e} Boolean) -> [a] ->{e} [Nonempty a]
     -  origin.List.groupSublistsBy.doc : Doc.Deprecated
     +  base.List.groupSublistsBy.doc   : Doc.Deprecated

     List.Nonempty.scanl : (a ->{e} a ->{e} a) -> Nonempty a ->{e} Nonempty a
     -  origin.List.Nonempty.scanl.doc : Doc.Deprecated
     +  base.List.Nonempty.scanl.doc   : Doc.Deprecated

     List.scanl : (b ->{e} a ->{e} b) -> b -> [a] ->{e} Nonempty b
     -  origin.List.scanl.doc : Doc.Deprecated
     +  base.List.scanl.doc   : Doc.Deprecated

     List.zipWith : (a ->{𝕖} b ->{𝕖} c) -> [a] -> [b] ->{𝕖} [c]
     -  origin.List.zipWith.doc : Doc.Deprecated
     +  base.List.zipWith.doc   : Doc.Deprecated

     Map.adjust : (v ->{e} v) -> k -> Map k v ->{e} Map k v
     -  origin.Map.adjust.doc : Doc.Deprecated
     +  base.Map.adjust.doc   : Doc.Deprecated

     Map.adjustWithKey : (k ->{e} v ->{e} v) -> k -> Map k v ->{e} Map k v
     -  origin.Map.adjustWithKey.doc : Doc.Deprecated
     +  base.Map.adjustWithKey.doc   : Doc.Deprecated

     Map.alter : (Optional v ->{e} Optional v) -> k -> Map k v ->{e} Map k v
     -  origin.Map.alter.doc : Doc.Deprecated
     +  base.Map.alter.doc   : Doc.Deprecated

     Map.breakOffMax : Map k v -> Optional ((k, v), Map k v)
     -  origin.Map.breakOffMax.doc : Doc.Deprecated
     +  base.Map.breakOffMax.doc   : Doc.Deprecated

     Map.breakOffMin : Map k v -> Optional ((k, v), Map k v)
     -  origin.Map.breakOffMin.doc : Doc.Deprecated
     +  base.Map.breakOffMin.doc   : Doc.Deprecated

     Map.foldLeft : (a ->{e} b ->{e} a) -> a -> Map k b ->{e} a
     -  origin.Map.foldLeft.doc : Doc.Deprecated
     +  base.Map.foldLeft.doc   : Doc.Deprecated

     Map.foldLeftWithKey : (a ->{e} k ->{e} b ->{e} a) -> a -> Map k b ->{e} a
     ↓
     Map.foldLeftWithKey : (a ->{e} k ->{f} b ->{g} a) -> a -> Map k b ->{e, f, g} a
     -  origin.Map.foldLeftWithKey.doc : Doc.Deprecated
     +  base.Map.foldLeftWithKey.doc   : Doc.Deprecated
     +  authors.daanleijen             : Author
     +  unisoncomputing2022            : License
     +  authors.andriypalamarchuk      : Author
     +  runarorama                     : Author
     +  datamapinternal                : License

     Map.foldRight : (a ->{e} b ->{e} b) -> b -> Map k a ->{e} b
     ↓
     Map.foldRight : (a ->{e} b ->{f} b) -> b -> Map k a ->{e, f} b
     -  origin.Map.foldRight.doc  : Doc.Deprecated
     +  authors.daanleijen        : Author
     +  authors.andriypalamarchuk : Author
     +  base.Map.foldRight.doc    : Doc.Deprecated
     +  runarorama                : Author
     +  datamapinternal           : License

     Map.foldRightWithKey : (k ->{e} a ->{e} b ->{e} b) -> b -> Map k a ->{e} b
     ↓
     Map.foldRightWithKey : (k ->{e} a ->{f} b ->{g} b) -> b -> Map k a ->{e, f, g} b
     -  origin.Map.foldRightWithKey.doc : Doc.Deprecated
     +  authors.daanleijen              : Author
     +  unisoncomputing2022             : License
     +  authors.andriypalamarchuk       : Author
     +  base.Map.foldRightWithKey.doc   : Doc.Deprecated
     +  runarorama                      : Author
     +  datamapinternal                 : License

     Map.getOrElse : v -> k -> Map k v -> v
     -  origin.Map.getOrElse.doc : Doc.Deprecated
     +  base.Map.getOrElse.doc   : Doc.Deprecated

     Map.intersect : Map k a -> Map k b -> Map k a
     -  origin.Map.intersect.doc : Doc.Deprecated
     +  base.Map.intersect.doc   : Doc.Deprecated

     Map.intersectWith : (a ->{e} b ->{e} c) -> Map k a -> Map k b ->{e} Map k c
     -  origin.Map.intersectWith.doc : Doc.Deprecated
     +  base.Map.intersectWith.doc   : Doc.Deprecated

     Map.intersectWithKey : (k ->{e} a ->{e} b ->{e} c) -> Map k a -> Map k b ->{e} Map k c
     -  origin.Map.intersectWithKey.doc : Doc.Deprecated
     +  base.Map.intersectWithKey.doc   : Doc.Deprecated

     Map.map : (a ->{e} b) -> Map k a ->{e} Map k b
     -  origin.Map.map.doc : Doc.Deprecated
     +  base.Map.map.doc   : Doc.Deprecated

     Map.mapKeysWith : (v ->{g} v ->{g} v) -> (k1 ->{g} k2) -> Map k1 v ->{g} Map k2 v
     ↓
     Map.mapKeysWith : (v ->{e1} v ->{e2} v) -> (k1 ->{e3} k2) -> Map k1 v ->{e1, e2, e3} Map k2 v
     -  origin.Map.mapKeysWith.doc : Doc.Deprecated
     +  authors.daanleijen         : Author
     +  unisoncomputing2022        : License
     +  authors.andriypalamarchuk  : Author
     +  runarorama                 : Author
     +  base.Map.mapKeysWith.doc   : Doc.Deprecated
     +  datamapinternal            : License

     Map.mapWithKey : (k ->{e} a ->{e} b) -> Map k a ->{e} Map k b
     -  origin.Map.mapWithKey.doc : Doc.Deprecated
     +  base.Map.mapWithKey.doc   : Doc.Deprecated

     Map.putGetWithKey : (k ->{e} v ->{e} v ->{e} v)
     -> k
     -> v
     -> Map k v
     ->{e} (Optional v, Map k v)
     ↓
     Map.putGetWithKey : (k ->{e1} v ->{e2} v ->{e3} v)
     -> k
     -> v
     -> Map k v
     ->{e1, e2, e3} (Optional v, Map k v)
     -  origin.Map.putGetWithKey.doc : Doc.Deprecated
     +  authors.daanleijen           : Author
     +  base.Map.putGetWithKey.doc   : Doc.Deprecated
     +  unisoncomputing2022          : License
     +  authors.andriypalamarchuk    : Author
     +  runarorama                   : Author
     +  datamapinternal              : License

     Map.putWithKey : (k ->{e} v ->{e} v ->{e} v) -> k -> v -> Map k v ->{e} Map k v
     ↓
     Map.putWithKey : (k ->{e1} v ->{e2} v ->{e3} v) -> k -> v -> Map k v ->{e1, e2, e3} Map k v
     -  origin.Map.putWithKey.doc : Doc.Deprecated
     +  authors.daanleijen        : Author
     +  unisoncomputing2022       : License
     +  base.Map.putWithKey.doc   : Doc.Deprecated
     +  authors.andriypalamarchuk : Author
     +  runarorama                : Author
     +  datamapinternal           : License

     Map.unionWithKey : (k ->{e} v ->{e} v ->{e} v) -> Map k v -> Map k v ->{e} Map k v
     ↓
     Map.unionWithKey : (k ->{e1} v ->{e2} v ->{e3} v) -> Map k v -> Map k v ->{e1, e2, e3} Map k v
     -  origin.Map.unionWithKey.doc : Doc.Deprecated
     +  authors.daanleijen          : Author
     +  unisoncomputing2022         : License
     +  authors.andriypalamarchuk   : Author
     +  runarorama                  : Author
     +  base.Map.unionWithKey.doc   : Doc.Deprecated
     +  datamapinternal             : License

     Map.unionWithKey.tests.commutative : [Result]
     ↓
     Map.unionWithKey.tests.commutative : [Result]
     +  authors.daanleijen        : Author
     +  unisoncomputing2022       : License
     +  authors.andriypalamarchuk : Author
     +  runarorama                : Author
     +  isTest                    : IsTest
     +  datamapinternal           : License

     Map.updateWithKey : (k ->{e} v ->{e} Optional v) -> k -> Map k v ->{e} Map k v
     ↓
     Map.updateWithKey : (k ->{g} v ->{h} Optional v) -> k -> Map k v ->{g, h} Map k v
     -  origin.Map.updateWithKey.doc : Doc.Deprecated
     +  authors.daanleijen           : Author
     +  unisoncomputing2022          : License
     +  authors.andriypalamarchuk    : Author
     +  runarorama                   : Author
     +  datamapinternal              : License
     +  base.Map.updateWithKey.doc   : Doc.Deprecated

     Nat.hammingWeight.test : [Result]
     ↓
     Nat.hammingWeight.test : [Result]
     +  unisoncomputing2022 : License
     +  runarorama          : Author
     +  isTest              : IsTest
     +  unisoncomputing2020 : License

     Nat.msb.test : [Result]
     ↓
     Nat.msb.test : [Result]
     +  unisoncomputing2022 : License
     +  runarorama          : Author
     +  isTest              : IsTest
     +  unisoncomputing2020 : License

     Set.map.test : [Result]
     ↓
     Set.map.test : [Result]
     +  unisoncomputing2022 : License
     +  runarorama          : Author
     +  isTest              : IsTest
     +  unisoncomputing2020 : License

     test.gen.either : '{Gen} a -> '{Gen} b -> '{Gen} Either a b
     ↓
     test.gen.either : '{Gen} a -> '{Gen} b -> '{Gen} Either a b
     +  unisoncomputing2022 : License
     +  ceedubs2020         : License
     +  either.doc          : Doc.Deprecated
     +  runarorama          : Author
     +  authors.ceedubs     : Author

     test.gen.functions.logic : '{Gen} (Boolean -> Boolean -> Boolean)
     ↓
     test.gen.functions.logic : '{Gen} (Boolean -> Boolean -> Boolean)
     -  origin.test.gen.functions.logic.doc : Doc.Deprecated
     +  unisoncomputing2022                 : License
     +  base.test.gen.functions.logic.doc   : Doc.Deprecated
     +  runarorama                          : Author
     +  unisoncomputing2020                 : License

     test.internals.v1.Test.modifyScope : (Test.Scope ->{g} Test.Scope) -> Test -> Test
     ↓
     test.internals.v1.Test.modifyScope : (Test.Scope -> Test.Scope) -> Test -> Test
     +  unisoncomputing2022 : License
     +  runarorama          : Author
     +  unisoncomputing2020 : License

     test.internals.v1.Test.modifyStatus : (Status ->{g} Status) -> Test ->{g} Test
     ↓
     test.internals.v1.Test.modifyStatus : (Status -> Status) -> Test -> Test
     +  unisoncomputing2022 : License
     +  runarorama          : Author
     +  unisoncomputing2020 : License

     test.pick : ['{Gen} a] -> '{Gen} a
     ↓
     test.pick : ['{Gen} a] -> '{Gen} a
     +  unisoncomputing2022 : License
     +  runarorama          : Author

     Tuple.at1 : Tuple a b -> a
     -  origin.Tuple.at1.doc : Doc.Deprecated
     +  base.Tuple.at1.doc   : Doc.Deprecated

     Tuple.at2 : Tuple a (Tuple b c) -> b
     -  origin.Tuple.at2.doc : Doc.Deprecated
     +  base.Tuple.at2.doc   : Doc.Deprecated

     Tuple.at3 : Tuple a (Tuple b (Tuple c d)) -> c
     -  origin.Tuple.at3.doc : Doc.Deprecated
     +  base.Tuple.at3.doc   : Doc.Deprecated

     Tuple.at4 : Tuple a (Tuple b (Tuple c (Tuple d e))) -> d
     -  origin.Tuple.at4.doc : Doc.Deprecated
     +  base.Tuple.at4.doc   : Doc.Deprecated

     Tuple.mapPair : ((a ->{g} b), (c ->{g} d)) -> (a, c) ->{g} (b, d)
     -  origin.Tuple.mapPair.doc : Doc.Deprecated
     +  base.Tuple.mapPair.doc   : Doc.Deprecated

    There were 769 auto-propagated updates.

     patch patch (added 35 updates,
    deleted 35)

**Comment by pchiusano** [comment]
Okay, we are closing this now in favor of fixing the typechecker to better handle the existing signatures, which was recently merged into trunk: https://github.com/unisonweb/unison/pull/2895
