### ISSUE TITLE
reading an environment variable is a bit awkward

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#73]
The only function that I see for reading an environment variable is:

```
builtin .base.io.getEnv.impl : .base.Text ->{.base.IO} Either Failure .base.Text
```

A couple of questions come to mind:

- What are the possible types of failure? Just that the environment variable isn't defined? If so, `Optional Text` seems like a more straightforward return type.
- Why `getEnv.impl` as opposed to just `getEnv`? Did we mean to add a `getEnv` helper that returns `Optional` or uses `Exception` instead of `Either`?

To close this issue out I think that we should either change what's there to be clearer or we should add some docs.

**Comment by ceedubs** [comment]
@runarorama and @rlmark: any thoughts?

**Comment by rlmark** [comment]
Hmmm, the pattern that I've seen elsewhere is that the `.impl` functions are coupled with a non impl function of the same name that uses `Exception` as the error type. 

My vote would be to add a non .impl `getEnv` function and then document that, in keeping with the pattern of other `.base` functions.

**Comment by runarorama** [comment]
Fixed in v3 branch
