### ISSUE TITLE
Add `video` and `frontMatter` functions for docs, and related types

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#76]
@hojberg will work on a PR for this

**Comment by aryairani** [comment]
Video! 🚀

**Comment by hojberg** [comment]
This will work with these Doc additions https://github.com/unisonweb/unison/pull/2946

**Comment by runarorama** [comment]
What is frontMatter?

**Comment by hojberg** [comment]
It's this little yaml config often seen at the top of markdown files for blogposts. Captures metadata like title, date, and tags. My intention was to use this to help convert our blog posts to docs.
