### ISSUE TITLE
A simple Complex Numbers library 

### ISSUE THREAD

**Issue by tarikozkanli** [unisonweb/base#77]
Hello,

This is a very simple api for reprsenting and manipulating complex numbers in Unison.

Below is the output of the create pull request command :+1: 

---------------------------
The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base:v2:.trunk https://github.com/tarik-ozkanli/allmyunisoncode
  
  Added definitions:
  
     structural type Complex.Complex
     Complex.Complex.Complex                : Float -> Float -> Complex
     Complex.>                              : ∀ test Complex.eq.ex1.
                                              test -> Complex.eq.ex1 -> [Result] (+1 metadata)
     Complex.add                            : Complex -> Complex -> Complex (+1 metadata)
     ┌ Complex.conj                         : Complex -> Complex (+1 metadata)
     └ Complex.conjugate                    : Complex -> Complex (+1 metadata)
     Complex.div                            : Complex -> Complex -> Complex (+1 metadata)
     ┌ Complex.>.doc                        : Doc (+1 metadata)
     └ Complex.eq.doc                       : Doc (+1 metadata)
     Complex.add.doc                        : Doc (+1 metadata)
     Complex.conj.doc                       : Doc (+1 metadata)
     Complex.div.doc                        : Doc
     Complex.im.doc                         : Doc (+1 metadata)
     Complex.mag.doc                        : Doc
     Complex.mult.doc                       : Doc
     Complex.re.doc                         : Doc (+1 metadata)
     Complex.recip.doc                      : Doc
     Complex.sqr.doc                        : Doc
     Complex.sub.tests.ex1                  : [Result] (+1 metadata)
     ┌ Complex.im                           : Complex -> Float (+1 metadata)
     └ Complex.imaginary                    : Complex -> Float (+1 metadata)
     ┌ Complex.mag                          : Complex -> Float (+1 metadata)
     └ Complex.magnitude                    : Complex -> Float (+1 metadata)
     ┌ Complex.mult                         : Complex -> Complex -> Complex (+1 metadata)
     └ Complex.multiply                     : Complex -> Complex -> Complex (+1 metadata)
     ┌ Complex.re                           : Complex -> Float
     └ Complex.real                         : Complex -> Float
     ┌ Complex.recip                        : Complex -> Complex (+1 metadata)
     └ Complex.reciprocal                   : Complex -> Complex (+1 metadata)
     Complex.sqr                            : Complex -> Complex (+1 metadata)
     ┌ Complex.sub                          : Complex -> Complex -> Complex (+1 metadata)
     └ Complex.subtract                     : Complex -> Complex -> Complex (+1 metadata)
     Complex.metadata.licenses.tozkanli2021 : License
  
     patch Complex.patch (added 230 updates)
-------------------------

Regards.

Tarık Özkanlı

**Comment by runarorama** [comment]
Thanks for this! 🌈⭐ 

I've cleaned this up a bit, and you can check my work by issuing

```
pull https://github.com/runarorama/ubase2:#1oidju2tj9 someNamespace
```
 somewhere in your codebase.
 
 I cleaned up the docs a little and removed the short name aliases (users can always add aliases if they want). Also you had a stray term called `>` and other things like that.
 
It would also be really awesome if you could add comparison (inequalities) and `Ordering` for `Complex`, as well as `pow` for general exponentiation (rather than just squares).

Ping me in the Slack if you want to sync up over video.

**Comment by tarikozkanli** [comment]
Hi Runar,

Thank you for evaluations.

**1. About ordering**
Complex numbers is not an **ordered field**. It does not have a **linear order**. Because of that i passed this feature.
**2. About computing powers**
In order to compute the power of a complex number efficiently we need to convert it to **polar form from our rectangular form**.  After that it is easy to compute the nth power by (and nth roots also) by multiplying the magnitude and the angle by the power. After that it can be converted again to rectangular form. But to do that we need **arctan, sin, cos trigonometric functions**. If we have these functions it can be implemented.

Tarık Özkanlı

**Comment by runarorama** [comment]
1. Of course! You're right. 😆 
2. We have arctan, sin, cos, etc under `Float`: https://share.unison-lang.org/latest/namespaces/unison/base/;/types/Float

**Comment by runarorama** [comment]
Conversion to/from polar form would also be a welcome addition, now that you mention it.

**Comment by tarikozkanli** [comment]
I will be on it.

Thank you.

**Comment by runarorama** [comment]
Looks like this is now a standalone library published here: https://share.unison-lang.org/@tarikozkanli/p/code/latest/namespaces/public/complex
