### ISSUE TITLE
Doc.Video and Doc.FrontMatter

### ISSUE THREAD

**Issue by hojberg** [unisonweb/base#79]
This adds a few new builtin types for `Embed` in Unison Doc:

* `Doc.Video` - For embedding video
* `Doc.MediaSource` (used within `Doc.Video`)
* `Doc.FrontMatter` - For embedding front matter

There's also 2 helper functions for making it easier to work with the types:

* `Doc.Video.video : Text -> Text -> Doc`
* `Doc.FrontMatter.frontMatter : [(Text, Text)] -> Doc`

Pull in the definitions and their docs with: 

```
pull git@github.com:hojberg/base-video-frontmatter.git:#chog49cigu
```

Note that I attempted to use `pull-request.create`, but after waiting 30 mins for it to finish, I gave up.

**Comment by hojberg** [comment]
Fixes https://github.com/unisonweb/base/issues/76

**Comment by pchiusano** [comment]
@hojberg is it really `Doc.FrrontMatter` or was that a typo from manually copying?

**Comment by hojberg** [comment]
thats a typo - its correct in the code

**Comment by runarorama** [comment]
Merged in v3 branch. 

⛳️❗️
