### ISSUE TITLE
Docs for `Code` and `Value` types

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#87]
Unison has some super cool capabilities for dynamic code loading. This PR documents the primitives: 

```
pull git@github.com:pchiusano/sketches:#413sn7k771 .somepr
```

And then assuming that looks good you can just `merge .somepr .base.trunk`.

Live preview of the docs:

https://share.unison-lang.org/latest/namespaces/pchiusano/prs/codedocs

**Comment by runarorama** [comment]
Merged to `v3` branch. 🌈⭐
