### ISSUE TITLE
Add `io.getSomeBytes` built-in, document it and `io.getBytes`

### ISSUE THREAD

**Issue by iamevn** [unisonweb/base#91]
For unisonweb/unison#3029

- Add `io.getSomeBytes`
- Add `io.getSomeBytes.impl` (alias to new built-in in unisonweb/unison#3029)
- Add docs for `io.getSomeBytes` and `io.getBytes`
- Add MIT license for myself

Pull this namespace (just a gist with these terms): `pull git@github.com:iamevn/unison-code:gists:#1d27ucagpi`

 ## Code review

   The changes summarized below are available for you to review, using the following command:

     pull-request.load https://github.com/unisonweb/base:v3:.trunk git@github.com:iamevn/unison-code:gists:#1d27ucagpi

   Added definitions:

      io.getBytes.doc          : Doc (+2 metadata)
      io.getSomeBytes.doc      : Doc (+2 metadata)
      io.getSomeBytes          : Handle -> Nat ->{IO, Exception} Bytes (+2 metadata)
      metadata.licenses.iamevn : License.Deprecated
      io.getSomeBytes.impl     : Handle -> Nat ->{IO} Either Failure Bytes

 Defined as:

     io.getSomeBytes : Handle -> Nat ->{IO, Exception} Bytes
     io.getSomeBytes = compose2 reraise getSomeBytes.impl

     builtin io.getSomeBytes.impl :
       .base.io.Handle -> .base.Nat ->{.base.IO} Either Failure .base.Bytes

     io.getBytes.doc =
       {{ ``getBytes h n`` reads up to ''n'' bytes from {type Handle} ''h''.

       {getBytes} blocks until either ''n'' bytes are read or ''EOF'' is reached. }}

     io.getSomeBytes.doc =
       {{
       ``getSomeBytes h n`` reads up to ''n'' bytes from {type Handle} ''h''.

       {getSomeBytes} will only block if there is nothing to be read from ''h'' and ''EOF'' has not
       been reached.
       }}

     metadata.licenses.iamevn = License [copyrightHolders.iamevn] [Year 2021, Year 2022] mit

**Comment by runarorama** [comment]
Merged in base namespace hash `#s5p5jn9j8e` 🌈⭐
