### ISSUE TITLE
Add `Sha1 : HashAlgorithm`

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#95]
https://github.com/unisonweb/unison/pull/3126#issuecomment-1159191701

**Comment by dfreeman** [comment]
I've got this in a (v5) codebase at `git@github.com:dfreeman/unison-codebase.git` under `.dfreeman.sha1`. It also includes some simple doc additions.

```
.> ls .dfreeman.sha1

  1. Sha1      (HashAlgorithm)
  2. Sha1/     (1 definition)
  3. Sha2_256/ (1 definition)
  4. Sha2_512/ (1 definition)
  5. Sha3_256/ (1 definition)
  6. Sha3_512/ (1 definition)
```

**Comment by runarorama** [comment]
Hey @dfreeman could you push these to https://share.unison-lang.org? I am having some trouble pulling your codebase from GitHub

**Comment by runarorama** [comment]
I've added some docs to these definitions.
