### ISSUE TITLE
(Byte)Array API

### ISSUE THREAD

**Issue by dolio** [unisonweb/base#96]
This adds a base API for the array primops added in [unison PR #3104](https://github.com/unisonweb/unison/pull/3104). It provides aliases for the builtin types/operations under `Raw` names, and wraps them with data types that track an offset+length for faster slicing operations.

I didn't do tests in the actual test category, but most of the docs contain code examples that exercise the functions.

I see that the unison PR isn't merged yet, due to some merge conflicts. I should have that resolved before too much longer though, and then this can be merged.

## Code review

  The changes summarized below are available for you to review, using the following
  command:

    pull-request.load https://github.com/unisonweb/base:v4:.trunk https://github.com/dolio/unison-codebase:.base.vector

  Added definitions:

     structural type data.Array a (+2 metadata)
     structural type mutable.Array g a (+2 metadata)
     unique type ArrayFailure
     structural type data.ByteArray (+2 metadata)
     structural type mutable.ByteArray g (+2 metadata)
     builtin type data.Array.Raw
     builtin type mutable.Array.Raw
     builtin type data.ByteArray.Raw
     builtin type mutable.ByteArray.Raw
     data.Array.Arr                      : Nat -> Nat -> data.Array.Raw a -> data.Array a
     data.ByteArray.BArr                 : Nat
                                         -> Nat
                                         -> data.ByteArray.Raw
                                         -> data.ByteArray
     mutable.Array.MArr                  : Nat
                                         -> Nat
                                         -> mutable.Array.Raw g a
                                         -> mutable.Array g a
     mutable.ByteArray.MBArr             : Nat
                                         -> Nat
                                         -> mutable.ByteArray.Raw g
                                         -> mutable.ByteArray g
     mutable.Scope.Raw.array             : Nat
                                         ->{mutable.Scope s} mutable.Array.Raw
                                           (mutable.Scope s) a
     io.Raw.array                        : Nat ->{IO} mutable.Array.Raw {IO} a
     mutable.Scope.Raw.arrayOf           : a
                                         -> Nat
                                         ->{mutable.Scope s} mutable.Array.Raw
                                           (mutable.Scope s) a
     io.Raw.arrayOf                      : a -> Nat ->{IO} mutable.Array.Raw {IO} a
     mutable.Scope.arrayOf               : a
                                         -> Nat
                                         ->{mutable.Scope s} mutable.Array
                                           {mutable.Scope s} a (+2 metadata)
     io.arrayOf                          : a
                                         -> Nat
                                         ->{IO} mutable.Array {IO} a (+2 metadata)
     mutable.Scope.byteArray             : Nat
                                         ->{mutable.Scope s} mutable.ByteArray
                                           {mutable.Scope s} (+2 metadata)
     io.byteArray                        : Nat ->{IO} mutable.ByteArray {IO} (+2 metadata)
     mutable.Scope.byteArrayOf           : Nat
                                         -> Nat
                                         ->{mutable.Scope s} mutable.ByteArray
                                           {mutable.Scope s} (+2 metadata)
     io.byteArrayOf                      : Nat
                                         -> Nat
                                         ->{IO} mutable.ByteArray {IO} (+2 metadata)
     mutable.Scope.Raw.bytearray         : Nat
                                         ->{mutable.Scope s} mutable.ByteArray.Raw
                                           (mutable.Scope s)
     io.Raw.bytearray                    : Nat ->{IO} mutable.ByteArray.Raw {IO}
     mutable.Scope.Raw.bytearrayOf       : Nat
                                         -> Nat
                                         ->{mutable.Scope s} mutable.ByteArray.Raw
                                           (mutable.Scope s)
     io.Raw.bytearrayOf                  : Nat -> Nat ->{IO} mutable.ByteArray.Raw {IO}
     data.Array.Raw.copyTo!              : mutable.Array.Raw g a
                                         -> Nat
                                         -> data.Array.Raw a
                                         -> Nat
                                         -> Nat
                                         ->{g, Exception} ()
     mutable.Array.Raw.copyTo!           : mutable.Array.Raw g a
                                         -> Nat
                                         -> mutable.Array.Raw g a
                                         -> Nat
                                         -> Nat
                                         ->{g, Exception} ()
     data.ByteArray.Raw.copyTo!          : mutable.ByteArray.Raw g
                                         -> Nat
                                         -> data.ByteArray.Raw
                                         -> Nat
                                         -> Nat
                                         ->{g, Exception} ()
     mutable.ByteArray.Raw.copyTo!       : mutable.ByteArray.Raw g
                                         -> Nat
                                         -> mutable.ByteArray.Raw g
                                         -> Nat
                                         -> Nat
                                         ->{g, Exception} ()
     data.Array.doc                      : Doc (+2 metadata)
     mutable.Array.doc                   : Doc (+2 metadata)
     mutable.ByteArray.doc               : Doc (+2 metadata)
     mutable.Array.Raw.doc               : Doc (+2 metadata)
     ┌ mutable.Scope.Raw.array.doc       : Doc (+2 metadata)
     └ io.Raw.array.doc                  : Doc (+2 metadata)
     ┌ mutable.Scope.Raw.arrayOf.doc     : Doc (+2 metadata)
     └ io.Raw.arrayOf.doc                : Doc (+2 metadata)
     ┌ mutable.Scope.arrayOf.doc         : Doc (+2 metadata)
     └ io.arrayOf.doc                    : Doc (+2 metadata)
     ┌ mutable.Scope.byteArray.doc       : Doc (+2 metadata)
     └ io.byteArray.doc                  : Doc (+2 metadata)
     ┌ mutable.Scope.byteArrayOf.doc     : Doc (+2 metadata)
     └ io.byteArrayOf.doc                : Doc (+2 metadata)
     ┌ data.Array.Raw.copyTo!.doc        : Doc (+2 metadata)
     └ mutable.Array.Raw.copyTo!.doc     : Doc (+2 metadata)
     ┌ data.ByteArray.Raw.copyTo!.doc    : Doc (+2 metadata)
     └ mutable.ByteArray.Raw.copyTo!.doc : Doc (+2 metadata)
     data.Array.drop.doc                 : Doc (+2 metadata)
     mutable.Array.drop!.doc             : Doc (+2 metadata)
     mutable.ByteArray.drop!.doc         : Doc (+2 metadata)
     mutable.Array.dropEnd!.doc          : Doc (+2 metadata)
     mutable.ByteArray.dropEnd!.doc      : Doc (+2 metadata)
     mutable.Array.freeze.doc            : Doc (+2 metadata)
     mutable.Array.Raw.freeze.doc        : Doc (+2 metadata)
     mutable.ByteArray.Raw.freeze.doc    : Doc (+2 metadata)
     mutable.Array.freeze!.doc           : Doc (+2 metadata)
     mutable.ByteArray.freeze!.doc       : Doc (+2 metadata)
     mutable.Array.Raw.freeze!.doc       : Doc (+2 metadata)
     mutable.ByteArray.Raw.freeze!.doc   : Doc (+2 metadata)
     data.Array.fromList.doc             : Doc (+2 metadata)
     data.ByteArray.fromList.doc         : Doc (+2 metadata)
     bug.impossible.doc                  : Doc (+2 metadata)
     ArrayFailure.raise.doc              : Doc (+2 metadata)
     data.Array.read.doc                 : Doc (+2 metadata)
     mutable.Array.read.doc              : Doc (+2 metadata)
     mutable.ByteArray.Raw.read16be.doc  : Doc (+2 metadata)
     mutable.ByteArray.Raw.read32be.doc  : Doc (+2 metadata)
     mutable.ByteArray.Raw.read64be.doc  : Doc (+2 metadata)
     data.ByteArray.read8.doc            : Doc (+2 metadata)
     mutable.ByteArray.read8.doc         : Doc (+2 metadata)
     data.Array.slice.doc                : Doc (+2 metadata)
     mutable.Array.slice!.doc            : Doc (+2 metadata)
     mutable.ByteArray.slice!.doc        : Doc (+2 metadata)
     ┌ mutable.Scope.thawArray.doc       : Doc (+2 metadata)
     └ io.thawArray.doc                  : Doc (+2 metadata)
     ┌ mutable.Scope.thawByteArray.doc   : Doc (+2 metadata)
     └ io.thawByteArray.doc              : Doc (+2 metadata)
     data.Array.toList.doc               : Doc (+2 metadata)
     data.ByteArray.toList.doc           : Doc (+2 metadata)
     mutable.Array.write.doc             : Doc (+2 metadata)
     data.ByteArray.write8.doc           : Doc (+2 metadata)
     mutable.ByteArray.write8.doc        : Doc (+2 metadata)
     data.Array.drop                     : Nat
                                         -> data.Array a
                                         ->{Exception} data.Array a (+2 metadata)
     mutable.Array.drop!                 : Nat
                                         -> mutable.Array g a
                                         ->{Exception} mutable.Array g a (+2 metadata)
     mutable.ByteArray.drop!             : Nat
                                         -> mutable.ByteArray g
                                         ->{Exception} mutable.ByteArray g (+2 metadata)
     mutable.Array.dropEnd!              : Nat
                                         -> mutable.Array g a
                                         ->{Exception} mutable.Array g a (+2 metadata)
     mutable.ByteArray.dropEnd!          : Nat
                                         -> mutable.ByteArray g
                                         ->{Exception} mutable.ByteArray g (+2 metadata)
     mutable.Array.freeze                : mutable.Array g a
                                         ->{g} data.Array a (+2 metadata)
     mutable.Array.Raw.freeze            : mutable.Array.Raw g a
                                         -> Nat
                                         -> Nat
                                         ->{g} data.Array.Raw a
     mutable.ByteArray.Raw.freeze        : mutable.ByteArray.Raw g
                                         -> Nat
                                         -> Nat
                                         ->{g} data.ByteArray.Raw
     mutable.Array.freeze!               : mutable.Array g a
                                         ->{g} data.Array a (+2 metadata)
     mutable.ByteArray.freeze!           : mutable.ByteArray g
                                         ->{g} data.ByteArray (+2 metadata)
     mutable.Array.Raw.freeze!           : mutable.Array.Raw g a ->{g} data.Array.Raw a
     mutable.ByteArray.Raw.freeze!       : mutable.ByteArray.Raw g
                                         ->{g} data.ByteArray.Raw
     data.Array.fromList                 : [a] -> data.Array a (+2 metadata)
     data.ByteArray.fromList             : [Nat] -> data.ByteArray (+2 metadata)
     bug.impossible                      : Request Exception a -> a (+2 metadata)
     ArrayFailure.raise                  : Text -> a ->{Exception} b (+2 metadata)
     data.Array.read                     : data.Array a
                                         -> Nat
                                         ->{Exception} a (+2 metadata)
     mutable.Array.read                  : mutable.Array g a
                                         -> Nat
                                         ->{g, Exception} a (+2 metadata)
     data.Array.Raw.read                 : data.Array.Raw a -> Nat ->{Exception} a
     mutable.Array.Raw.read              : mutable.Array.Raw g a -> Nat ->{g, Exception} a
     data.ByteArray.Raw.read16be         : data.ByteArray.Raw -> Nat ->{Exception} Nat
     mutable.ByteArray.Raw.read16be      : mutable.ByteArray.Raw g
                                         -> Nat
                                         ->{g, Exception} Nat
     data.ByteArray.Raw.read32be         : data.ByteArray.Raw -> Nat ->{Exception} Nat
     mutable.ByteArray.Raw.read32be      : mutable.ByteArray.Raw g
                                         -> Nat
                                         ->{g, Exception} Nat
     data.ByteArray.Raw.read64be         : data.ByteArray.Raw -> Nat ->{Exception} Nat
     mutable.ByteArray.Raw.read64be      : mutable.ByteArray.Raw g
                                         -> Nat
                                         ->{g, Exception} Nat
     data.ByteArray.read8                : data.ByteArray
                                         -> Nat
                                         ->{Exception} Nat (+2 metadata)
     mutable.ByteArray.read8             : mutable.ByteArray g
                                         -> Nat
                                         ->{g, Exception} Nat (+2 metadata)
     data.ByteArray.Raw.read8            : data.ByteArray.Raw -> Nat ->{Exception} Nat
     mutable.ByteArray.Raw.read8         : mutable.ByteArray.Raw g
                                         -> Nat
                                         ->{g, Exception} Nat
     data.Array.slice                    : Nat
                                         -> Nat
                                         -> data.Array a
                                         ->{Exception} data.Array a (+2 metadata)
     mutable.Array.slice!                : Nat
                                         -> Nat
                                         -> mutable.Array g a
                                         ->{Exception} mutable.Array g a (+2 metadata)
     mutable.ByteArray.slice!            : Nat
                                         -> Nat
                                         -> mutable.ByteArray g
                                         ->{Exception} mutable.ByteArray g (+2 metadata)
     mutable.Scope.thawArray             : data.Array a
                                         ->{mutable.Scope s} mutable.Array
                                           {mutable.Scope s} a (+2 metadata)
     io.thawArray                        : data.Array a
                                         ->{IO} mutable.Array {IO} a (+2 metadata)
     mutable.Scope.thawByteArray         : data.ByteArray
                                         ->{mutable.Scope s} mutable.ByteArray
                                           {mutable.Scope s} (+2 metadata)
     io.thawByteArray                    : data.ByteArray
                                         ->{IO} mutable.ByteArray {IO} (+2 metadata)
     data.Array.toList                   : data.Array a -> [a] (+2 metadata)
     data.ByteArray.toList               : data.ByteArray -> [Nat] (+2 metadata)
     mutable.Array.write                 : mutable.Array g a
                                         -> Nat
                                         -> a
                                         ->{g, Exception} () (+2 metadata)
     mutable.Array.Raw.write             : mutable.Array.Raw g a
                                         -> Nat
                                         -> a
                                         ->{g, Exception} ()
     mutable.ByteArray.Raw.write16be     : mutable.ByteArray.Raw g
                                         -> Nat
                                         -> Nat
                                         ->{g, Exception} ()
     mutable.ByteArray.Raw.write32be     : mutable.ByteArray.Raw g
                                         -> Nat
                                         -> Nat
                                         ->{g, Exception} ()
     mutable.ByteArray.Raw.write64be     : mutable.ByteArray.Raw g
                                         -> Nat
                                         -> Nat
                                         ->{g, Exception} ()
     data.ByteArray.write8               : data.ByteArray
                                         -> Nat
                                         -> Nat
                                         ->{Exception} data.ByteArray (+2 metadata)
     mutable.ByteArray.write8            : mutable.ByteArray g
                                         -> Nat
                                         -> Nat
                                         ->{g, Exception} () (+2 metadata)
     mutable.ByteArray.Raw.write8        : mutable.ByteArray.Raw g
                                         -> Nat
                                         -> Nat
                                         ->{g, Exception} ()

**Comment by dolio** [comment]
I've added a few more array functions to the namespace that came up when I was getting back into compiler work. Let me know if there are any problems, since there have been some changes with the tooling in the interim. Hopefully I pushed the new stuff correctly.

**Comment by runarorama** [comment]
Merged into https://share-next.unison-lang.org/users/unison/code/latest/namespaces/public/base/main

🌈⭐
