### ISSUE TITLE
M3 release isn't self-contained

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/base#99]
If you run `namespace.dependencies`, you'll see a few things reported as nameless in the `M3` context.

**Comment by stew** [comment]
I think that we should try to fix this up before an M5 release. @runarorama any chance you could spend some time cleaning this up?

when you are in the base directory `namespace.dependencies` should not show any external dependencies

**Comment by runarorama** [comment]
I can take a look tonight.

**Comment by runarorama** [comment]
There's a lot of deleted `Doc.Deprecated` docs still linked to terms in `base`. These are old docs that no longer exist, but the links to the deleted values still exist. Maybe somebody could help me come up with a SQL query to unlink these in one fell swoop.

Basically we want to delete all links to values of type `Doc.Deprecated`.

**Comment by aryairani** [comment]
Unfortunately there’s no way to do this with a SQL query without a codebase rewrite that’s a bit further down the road at least. Awk or some other text processor might be our best bet for now. e.g. take the output of namespace.dependencies and convert it to a bunch of unlink commands to paste into ucm

**Comment by ChrisPenner** [comment]
I'd be game to take a look at this with you some time next week, the awk thing would be great if that works, if it doesn't work out maybe I can just write a custom throw-away migration for this that we don't even merge :shrug:

**Comment by runarorama** [comment]
I resolved this by unlinking the deprecated docs manually.

**Comment by runarorama** [comment]
```
.base> namespace.dependencies

  This namespace has no external dependencies.
```
